### ISSUE TITLE
Problem: we have no way of easily synchronizing labels across repositories

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1002]
- See the [GitHub labels API docs](https://developer.github.com/v3/issues/labels/)
- See the [NPM github label sync script](https://www.npmjs.com/package/github-label-sync)

**Comment by ross-spencer** [comment]
@sallain is Codetree doing this for us now? Perhaps we can close this one?

**Comment by sallain** [comment]
Yes, Codetree does do this for us! I have done some of the cleanup, enough that I think we can close this.
