### ISSUE TITLE
Problem: AM17 isn't using MediaConch v18.03

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1006]
We've agreed on making this change in time for the 1.7 release.

See https://github.com/artefactual/archivematica/issues/966#issuecomment-374861980 for more details.

Checklist:

- [x] [AM PR 1009 - MC 18.03 for Docker and Ansible (Ubuntu) in stable/1.7.x](https://github.com/artefactual/archivematica/pull/1009)
- [x] [AM PR 1010 - MC 18.03 for Docker and Ansible (Ubuntu) in qa/1.x](https://github.com/artefactual/archivematica/pull/1010)
- [x] [AM-packbuild Issue 141 - MC 18.03 for CentOS/Redhat and packages](https://github.com/artefactual-labs/am-packbuild/issues/141)
- [x] https://github.com/artefactual/archivematica/pull/1019
- [x] Confirm that Docker deploys work for stable and qa with MC v 18.03 and the base image complication.

**Comment by ross-spencer** [comment]
@jrwdunham re: trying to rebuild the `stable/1.7.x` image. I am still seeing other non-Mediaconch failures, related t this issue: https://github.com/artefactual-labs/am/issues/45 so for QA, perhaps @sevein or @ablwr could give it a whirl? I'll prep something for Avalon in the new week.

**Comment by ross-spencer** [comment]
Hi @jrwdunham, I am also not seeing the upgrade happen with `qa/1.x`, having just removed and rebuild all my containers, when I build from the following commit:

```
commit 253a998c40b789ef79aab3fb77dfc39b76a27e1e (HEAD -> qa/1.x, origin/qa/1.x, origin/dev/issue-1006-update-mediaconch-18.03)
Author: Joel Dunham <jrwdunham@gmail.com>
Date:   Thu Mar 22 11:16:57 2018 -0700

    MCPClient: update MediaConch to v.18.03
```

And log into the container, I see:

```
ross-spencer@artefactual:~/git/artefactual-labs/am/compose:$ sudo docker-compose exec archivematica-mcp-client bash
[sudo] password for ross-spencer: 
archivematica@0c69e99c9895:/$ mediaconch -v
MediaConch Command Line Interface 17.12
archivematica@0c69e99c9895:/$ 
```

I can see the correct Mediaconch references in the Docker image so not sure what's happening. 

Will try and debug if I get more time.

**Comment by ross-spencer** [comment]
@jrwdunham @ablwr unless this is a Mediaconch error? Was a `17.12` ever available? https://mediaarea.net/MediaConch/Download/Ubuntu

**Comment by ablwr** [comment]
It... was... 🤔 CC: @JeromeMartinez

**Comment by sevein** [comment]
@jrwdunham question about #1010: MCPClient.Dockerimage is still based on`artefactual/archivematica-mcp-client-base:20180315.01`. The repo still shows that as the latest tag available: https://hub.docker.com/r/artefactual/archivematica-mcp-client-base/tags/.

https://github.com/artefactual/archivematica/blob/253a998c40b789ef79aab3fb77dfc39b76a27e1e/src/MCPClient.Dockerfile#L1

Correct me if I'm wrong but I think that we need to:
- Build https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient-base.Dockerfile
- Push it to the registry
- Update MCPClient.Dockerfile pointing to the new tag.

**Comment by jrwdunham** [comment]
@sevein @ross-spencer yes, I forgot to push the new base image for qa/1.x deploys. After https://github.com/artefactual/archivematica/pull/1020 is merged, a deploy of qa/1.x with docker compose should show MC v. 18.03 as installed.

**Comment by jrwdunham** [comment]
I'm closing this. If future QA testing shows that MC 18.03 is not installed in all of packages, Ansible and Docker, then we can address that later.
