### ISSUE TITLE
AIC number doesn't persist in metadata entry form

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#1007]
Part of the AIC workflow requires users to add the AIC number to the transfer, usually through the metadata entry form in the GUI:

![screenshot of archivematica dashboard metadata entry form -](https://user-images.githubusercontent.com/4612276/37736908-6c969a14-2d0f-11e8-8189-caf771fdc0a7.jpg)

Entering the data and clicking save creates a new metadata entry, as expected. However, if you then edit the form, the AIC number has disappeared.

The AIC number IS making it to the AIP METS, however. It seems to be the form that is malfunctioning, not the creation of the AIC number itself.

Tested on AM 1.7 (centOS and ubuntu) and on Chrome and Firefox.

**Comment by sallain** [comment]
Closed in favour of archivematica/Issues#311

**Comment by ross-spencer** [comment]
(Was never previously closed, closing now!)
