### ISSUE TITLE
Problem: migration conflict between AM17 and AM18

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1011]
AM18 needs to have the migrations rearranged, e.g. 0050 should become 0049, 0049 should become 0050 and so on...

#### stable/1.7.x migrations:
- ...
- 0048_fix_upload_qubit_setting.py
- 0049_change_pointer_file_filegrpuse.py

#### qa/1.x migrations:
- ...
- 0048_fix_upload_qubit_setting.py
- 0049_remove_magic_links.py (**never applied**)
- 0050_change_pointer_file_filegrpuse.py

**Comment by ross-spencer** [comment]
@sevein do you have a little more information for this ticket on why? (sorry, newbie question I guess)

**Comment by sevein** [comment]
A number of things need to happen for this to become a problem but it's very likely:
- Archivematica v1.8.0 is released at some point from the `qa/1.x` branch.
- The user installs Archivematica v1.7.0. The database 0049 migration was applied: 0049_change_pointer_file_filegrpuse.py.
- The user upgrades to Archivematica v1.8.0. Next migration available that is applied: 0050.

This results in the following `Problem: 0049_remove_magic_links.py is never applied`.
I decided to go with wider description for the issue.

**Comment by jhsimpson** [comment]
This issue is duplicated by https://github.com/archivematica/Issues/issues/54 - however that issue is in the new Issues repository, so I am closing this one in favour of that one.
