### ISSUE TITLE
Problem: Some unit tests use Python assert instead of unittest.TestCase asserts

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#1013]
Ref: https://docs.python.org/3.6/library/unittest.html#basic-example

> The crux of each test is a call to `assertEqual()` to check for an expected result; `assertTrue()` or `assertFalse()` to verify a condition; or `assertRaises()` to verify that a specific exception gets raised. These methods are used instead of the assert statement so the test runner can accumulate all test results and produce a report.

E.g. https://github.com/artefactual/archivematica/search?utf8=%E2%9C%93&q=assert&type=

Those test classes running `from django.test import TestCase` inherit from `unittest` so replacing assert calls should be easy enough here, e.g. https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/dashboard/tests/test_filesystem_ajax.py

Really just raising the question. The other output of the unittest class asserts is that user friendly messages are created for us, where we use a lot of plain asserts. 

If we decide it might be nicer to use the `unittest` asserts then perhaps it can be incorporated into future style guidelines where there is an opportunity to modify test cases as we go.

**Comment by sevein** [comment]
It's not plain `assert`, it's the magic version of `assert` provided by pytest.
pytest is very core in AM at this point, I wouldn't consider a different option. It's great.
More here: https://docs.pytest.org/en/latest/assert.html.

**Comment by ross-spencer** [comment]
I see. Thanks @sevein

**Comment by sevein** [comment]
I think @ross-spencer there is still a case for using some of the assert functions provided by `TestCase`, they can be useful. It think they can coexist.
