### ISSUE TITLE
Problem: Regression where status code lookup doesn't happen, Ingest/Microservices page

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#1018]
**AM 1.6** (status code renders as text)

![image](https://user-images.githubusercontent.com/1880412/37888007-7f2ad292-3121-11e8-840c-fcc0c76ae15c.png)

**AM 1.7** (status code renders as integer)

![image](https://user-images.githubusercontent.com/1880412/37888017-8b931d14-3121-11e8-80c0-2524f5324862.png)

**URI in your system to recreate:**

`http://<am-uri>/ingest/<UUID>/microservices`

**Previous effort:**

Relevant commit to pick up again from (this implemented the superior status code, but we should probably have a lookup on top of this for the UI), https://github.com/artefactual/archivematica/commit/829ae043f468e1b29b266e880b81f1a174ff6d97

**Comment by sevein** [comment]
Related: https://github.com/JiscRDSS/archivematica/pull/43

**Comment by ross-spencer** [comment]
No longer an issue (see below) not clear which commit it was resolved under, but I do remember conversations around this topic. 

![image](https://user-images.githubusercontent.com/1880412/50083642-b57c9700-01f4-11e9-911b-3a915064ded0.png)

Also note: The two comparison screenshots in the original ticket are incorrect and show the same screen, so do not really provide a valuable comparison.
