### ISSUE TITLE
Bug: "open" PREMIS rights dates causing AIP indexing failure

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#1033]
To reproduce:
- create a SIP with PREMIS rights that have an open end date

Result: 
- AIP fails to index with this error:

ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')
ERROR: error trying to index.
TransportError(400, u'MapperParsingException[failed to parse [mets.ns0:mets_dict_list.ns0:amdSec_dict_list.ns0:rightsMD_dict_list.ns0:mdWrap_dict_list.ns0:xmlData_dict_list.ns5:rightsStatement_dict_list.ns5:otherRightsInformation_dict_list.ns5:otherRightsApplicableDates_dict_list.ns5:endDate]]; nested: MapperParsingException[failed to parse date field [OPEN], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "OPEN"]; ')

**Comment by jrwdunham** [comment]
This is related to the following issues and PRs:

- [Internal Redmine issue 9330: "AIP failed to index"](https://projects.artefactual.com/issues/9330)
- [Don’t autodetect METS mappings in ElasticSearch](https://github.com/artefactual/archivematica/pull/402)

**Comment by jrwdunham** [comment]
In order to reproduce this issue, it is necessary to do the following.

1. Create an AIP and add Rights and DC metadata where the Rights metadata uses real dates for the start and end date values. This triggers Elasticsearch into auto-detecting the type of those fields as dates.
2. Create a second AIP and add Rights and DC metadata except that this time check the "Open End Date" checkbox instead of providing a date in the "Policy end date" field. This will cause a failure at "Index AIP" because Elasticsearch will be given `"OPEN"` and will be unable to parse it as a date.

**Comment by jrwdunham** [comment]
@sallain 

To QA, follow the instructions in comment https://github.com/artefactual/archivematica/issues/1033#issuecomment-379051848 above. Actually, you can follow the more detailed instructions at https://github.com/artefactual/archivematica/pull/1045#issuecomment-379054879. Optionally also follow the instructions at https://github.com/artefactual/archivematica/pull/1045#issuecomment-379150477.

Note: it is important that the ES index be cleared before QAing this. So if you're not working with a fresh install, you have to send a DELETE request to the Elasticsearch process against the `aips` index.

**Comment by sallain** [comment]
Looks good!
