### ISSUE TITLE
Problem: archivespaceids.csv attempts to match derivatives to originals

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1034]
In the context of Archivematica/ArchivesSpace integration, a user-supplied archivesspaceids.csv file encodes how to match user-supplied **access derivatives** to ArchivesSpace resource IDs. However, when AM attempts to upload a DIP to ArchivesSpace, it parses the METS file for **originals** and attempts to match those original UUIDs to ArchivesSpace resource IDs but it fails (raises a `KeyError` exception) because there are only access derivative UUIDs to match against.

Archivematica users at RAC confirm that they are looking to match individual access files from a DIP to an archival_object in ArchivesSpace and believe that this feature has worked for them in the past.

This issue could be fixed by modifying the "upload DIP" logic to parse the METS file for access derivatives (instead of originals).

**Comment by jrwdunham** [comment]
Related to internal Redmine issue 12006.

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rockefeller](https://trello.com/c/iVH3WbnY/6-rockefeller)

**Comment by ablwr** [comment]
I'm reviewing this ticket now and I would like to see @jraddaoui's documentation change from last December merged in as well: https://github.com/artefactual/archivematica-docs/pull/59/files
