### ISSUE TITLE
GPG key is not right for mediaconch

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica#1037]
On step 6 of the CentOS installation docs [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-centos/#install-pkg-centos), `archivematica-mcp-client` fails to install because `mediaconch` fails to install.  The error message is as follows:

```
Install  1 Package (+176 Dependent packages)

Total size: 394 M
Installed size: 772 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/archivematica-extras/packages/mediaconch-18.03.x86_64.RHEL_7.rpm: Header V3 DSA/SHA1 Signature, key ID 0c9a6ded: NOKEY
Retrieving key from https://packages.archivematica.org/1.7.x/key.asc


The GPG keys listed for the "archivematica-extras" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: mediaconch-18.03-3.1.x86_64
 GPG Keys are configured as: https://packages.archivematica.org/1.7.x/key.asc
```

This is likely related to the recent change in #1032 .

**Comment by sevein** [comment]
@scollazo 🏓

**Comment by scollazo** [comment]
Packages can be re-signed using `rpm --addsign <package.rpm>`. Also, you can verify a signed package with `rpm -K <package.rpm>`

You can find more info about rpm signatures management in [CentOS docs](https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-check-rpm-sig.html)

**Comment by sevein** [comment]
ok thanks I'll try - I've deleted your message accidentally!

**Comment by sevein** [comment]
Ok it worked, now archivematica-mcp-client when installed it brings
- `mediaconch.x86_64 0:18.03.1-1.1`
- `libmediainfo.x86_64 0:18.03.1-2.1`
- `libzen.x86_64 0:0.4.37-2.1`

Resigned with `rpmsign` like @scollazo explained.

I've just deployed a new VM following the instructions in https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-centos/ and it worked.

**Comment by jpellman** [comment]
I've verified that `mediaconch` (and consequently `archivematica-mcp-client`) is installing without any hitches.

**Comment by mamedin** [comment]
Thanks @jpellman
