### ISSUE TITLE
Problem: verify_checksums in verify_aip may now be breaking metadata-only re-ingest

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1038]
Further investigation required. To re-create, create an AIP and then attempt a metadata-only re-ingest. I saw this error in the verifyAIP_v1.0 micro-service:

    Unable to find expected path objects/Landing_zone.jpg for file 0fd275c7-a38e-458e-b021-6b23eb1ab6f9 in the following mapping from file paths to checksums that was extracted from Bag manifest file /var/archivematica/sharedDirectory/tmp/f1752d5a-8e12-44fe-8fc5-33e6ad9a2a46/wed1-f1752d5a-8e12-44fe-8fc5-33e6ad9a2a46/manifest-sha256.txt:
    {'METS.f1752d5a-8e12-44fe-8fc5-33e6ad9a2a46.xml': '4792aadef316b7a08b564e78fec2bc49f09b40e6d8ab757c44f312fa2d02cea0',
     'README.html': '63a3a1295b5175d6b726e78660da44d4bdc0049f39eb9b951e6ca67d26c99270',
     'logs/clamAVScan.txt': '4c43816fecb392753a8efa03b1cedfbb9753d879fae4b5c3e013e292bc98b403',
     'logs/filenameCleanup.log': 'f9d75bcfb88ad2c7f981b6f8f21d6dd4d3782b6bec0c70c90c07811a515a90d6',
     'objects/submissionDocumentation/METS.f1752d5a-8e12-44fe-8fc5-33e6ad9a2a46.xml': '30c27221d88faf625e4aa54b1f1a23aad26c0b8778c7b059fefb34e1b605165c'}

**Comment by sevein** [comment]
I suspect that this may have been solved by https://github.com/artefactual/archivematica/pull/1152.

**Comment by jrwdunham** [comment]
Thanks @sevein. Yes, PR 1152 should fix this and this issue is better described by https://github.com/artefactual/archivematica/issues/1150. I'm closing this and will leave 1150 as the issue that describes this problem.
