### ISSUE TITLE
Path for Python Virtual Env Interpreter Messed Up for Gunicorn After Ubuntu 16.04 Installation

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica#1042]
I tried a fresh install of Ubuntu 16.04 this morning again using the instructions [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-ubuntu/#ubuntu-16-04-xenial-installation-instructions).  All looked well until step 13.  After this step, I performed a reboot just to verify that all the services would start up successfully if a reboot was ever needed, and the Archivematica dashboard / gunicorn seems to have encountered an issue:

```
● archivematica-dashboard.service - Archivematica Dashboard
   Loaded: loaded (/lib/systemd/system/archivematica-dashboard.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-04-05 14:54:07 UTC; 2min 20s ago
  Process: 1235 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 1218 ExecStart=/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/gunicorn --config /etc/archivematica/dashboard.gunicorn-config.py wsgi:application (code=exited, status=127)
 Main PID: 1218 (code=exited, status=127)

Apr 05 14:54:07 ip-172-31-37-233 systemd[1]: Started Archivematica Dashboard.
Apr 05 14:54:07 ip-172-31-37-233 systemd[1]: archivematica-dashboard.service: Main process exited, code=exited, status=127/n/a
Apr 05 14:54:07 ip-172-31-37-233 systemd[1]: archivematica-dashboard.service: Unit entered failed state.
Apr 05 14:54:07 ip-172-31-37-233 systemd[1]: archivematica-dashboard.service: Failed with result 'exit-code'.
```

Running the failed command manually gives the following:

```
root@ip-172-31-37-233:~# /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/gunicorn --config /etc/archivematica/dashboard.gunicorn-config.py
/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/gunicorn: 2: exec: /src/src/archivematica/src/dashboard/debian/archivematica-dashboard/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python: not found
```

And /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/gunicorn appears as follows:

```
#!/bin/sh
'''exec' /src/src/archivematica/src/dashboard/debian/archivematica-dashboard/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys

from gunicorn.app.wsgiapp import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

**Comment by sevein** [comment]
Thanks for the detailed report! I think this belongs to am-packbuild but it's ok here too.

This likely related to the recent changes we've made to our packages so the virtual environments live in a new location: `/usr/share/archivematica/virtualenvs/archivematica-dashboard` and so on. 

We basically feed [dh-virtualenv](https://github.com/spotify/dh-virtualenv) with an environment string called `DH_VIRTUALENV_INSTALL_ROOT` indicating the new location (see commit [85fab4](https://github.com/artefactual-labs/am-packbuild/commit/85fab4a65c19dbc3e330227aab6016ff903d9e65)).
I wonder if dh-virtualenv isn't working as expected. Perhaps it'd be worth trying dh-virtualenv's latest release 1.0 to see if that fixes the problem.

@scollazo has more experience than I do with dh-virtualenv so I'm hoping he knows more about it.

**Comment by sevein** [comment]
I've confirmed that dh-virtualenv 1.0 solves the issue with the shebangs.

I've tried two ways to introduce dh-virtualenv 1.0 in our build environments:

1. Update base image to `ubuntu:artful` (which provides dh-virtualenv 1.0)
2. Build dh-virtualenv 1.0 and install manually with

    ```Dockerfile
    # Build dh-virtualenv 1.0 package and install.
    # This version is needed but not provided until ubuntu:artful.
    RUN set -ex \
        && git clone https://github.com/spotify/dh-virtualenv.git \
        && cd dh-virtualenv \
        && yes | mk-build-deps -ri \
        && dpkg-buildpackage -us -uc -b \
        && dpkg -i ../dh-virtualenv_1.0-1_all.deb
    ```

@scollazo is planning to make this even easier by publishing the dh-virtualenv package for both trusty and xenial in our own public package repositories.

**Comment by sevein** [comment]
@jpellman I think that the solution is pretty close to ready. We have new packages working excepting the archivematica-storage-service package, that one is still having the issue with the shebangs and I'm hoping that this PR will solve the problem: https://github.com/artefactual-labs/am-packbuild/pull/159. I've tried to build locally and it's working:

```
cat ./usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/gunicorn
#!/usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from gunicorn.app.wsgiapp import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

So to be clear, this is already working: http://jenkins-ci.archivematica.org/repos/apt/release-1.7-xenial/archivematica-dashboard_1.7.0~rc.4-8-gb82e9fd_amd64.deb. Same for the other Archivematica packages.

This is still broken (Storage Service): http://jenkins-ci.archivematica.org/repos/apt/release-0.11-xenial/archivematica-storage-service_0.11.0~rc.7_amd64.deb but my PR suggests a potential solution.

**Comment by sevein** [comment]
You're right.
