### ISSUE TITLE
Problem: pressing Enter in Archival Storage tab search does not execute the current search

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1044]
it executes the previous one.

**Comment by ross-spencer** [comment]
Marking as `Severity:High` for discussion for inclusion in `1.9` as a PR from @replaceafill exists to resolve this issue.

**Comment by ross-spencer** [comment]
This is a very popular issue! Closing in favor of https://github.com/archivematica/Issues/issues/271 simply because it is in he newer issues repo.
