### ISSUE TITLE
Problem: verify transfer checksums succeeding without verifying the transfer checksums

### ISSUE THREAD

**Issue by bb233** [artefactual/archivematica#1061]
System: Archivematica 1.6.1, Storage Service 0.10.1, on CentOS 7

What I am doing: 

Testing the ability of Archivematica to detect corrupted files in standard transfers, using the metadata/checksum.sha256 file in the transfer. Specifically, we are creating a checksum.sha256 file and editing the checksums in the file. We also inadvertently replaced the spaces separating checksum from filename with a tab.

What I expected: 

The verify transfer checksums microservice to fail with some sort of indication that there was an invalid checksum.

What I saw: 

The verify transfer checksums microservice to succeed without visible error, and the transfer to proceed.
Digging into the verify transfer checksum microservice and looking at the generated report for the "verify metatdata directory checksums" task, I found the following STDERR output:

> sha256deep: /var/archivematica/sharedDirectory/currentlyProcessing/bb_bad_checksum-055fa458-2fe6-4bed-a179-8868e63b907d/metadata/checksum.sha256: Unable to find any hashes in file, skipped.
> sha256deep: Unable to load any matching files.
> Try `sha256deep -h` for more information.
> sha256deep: /var/archivematica/sharedDirectory/currentlyProcessing/bb_bad_checksum-055fa458-2fe6-4bed-a179-8868e63b907d/metadata/checksum.sha256: Unable to find any hashes in file, skipped.
> sha256deep: Unable to load any matching files.
> Try `sha256deep -h` for more information.

What else I tried:

I get similar results when using md5 checksums with tab separators, when using UTF-16 encoding, when using UTF-8 with BOMs, and other cases where the format _looks_ right in a text editor

What I think is going on:

The issue seems to be that if sha256deep fails to parse the checksum file, because it is in an unsupported format, it reports "unable to find hashes, skipped", and Archivematica isn't seeing that as an error.

Why I think this is a problem:

The checksum files are supposed to ensure transfer fixity, and yet when they exist but are themselves too corrupted to read, Archivematica silently ignores them and claims to have verified fixity when it hasn't.

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Artefactual (internal)](https://trello.com/c/eCHD7L5W/14-artefactual-internal)

**Comment by ross-spencer** [comment]
Marking as `Severity:High` for discussion about inclusion in `1.9`. (The ticket was already previously marked as `Severity:Critical`.

**Comment by sallain** [comment]
I have tested several scenarios:

* Checksums where there is an obvious error (removed a character from the checksum)

```
md5: comparison exited with status: 1. Please check the formatting of the checksums or integrity of the files.
md5: objects/copy.txt: FAILED
```

* Checksum file encoded as UTF-16 

```
md5: comparison exited with status: 1. Please check the formatting of the checksums or integrity of the files.
```

* Two objects in the transfer but a checksum for only one of them.

```
Comparison failed with 1 checksum lines and 2 transfer files.
```

* One object in the transfer but checksums for two items

```
md5: Comparison failed with 2 checksum lines and 1 transfer files
```

* Checksum file has bad formatting (I removed one space between the hash and the file)

```
Comparing transfer checksums with the supplied sha512 file
sha512: comparison exited with status: 1. Please check the formatting of the checksums or integrity of the files.
sha512:  objects/small.txt: FAILED open or read
```

I carried out the same series of tests with sha256, sha512 and sha1, just to be on the safe side. The job is now catching the errors described by @bb233 and the ones further described by @ross-spencer.
