### ISSUE TITLE
Problem: verifyAIP_v1.0's new checksum verification breaks re-ingest 

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1067]
The new changes brought in by https://github.com/artefactual/archivematica/pull/1012 appear to be breaking (full) re-ingest. The checksum verification looks in the database for the files of the AIP and seeks to compare those files (paths and checksums) to the information in the Bag manifest file. However, it appears to be erroneously doing the above using superseded files (derivatives) from the first ingest.

See this error message:

    Unable to find expected path objects/MARBLES-81cf9612-fca8-4464-9a67-59be51e80463.tif for file 81cf9612-fca8-4464-9a67-59be51e80463 in the following mapping from file paths to checksums that was extracted from Bag manifest file /var/archivematica/sharedDirectory/tmp/d4a6c7b3-831a-4885-a031-b675d7f7a630/fri2-d4a6c7b3-831a-4885-a031-b675d7f7a630/manifest-sha256.txt: {'METS.d4a6c7b3-831a-4885-a031-b675d7f7a630.xml': 'c3343f7b0cae957de8784b086e80da01a06d54b12f7711c8187f3f71def5ea41',
     'README.html': '63a3a1295b5175d6b726e78660da44d4bdc0049f39eb9b951e6ca67d26c99270',
     'logs/clamAVScan.txt': 'c019eb7a71cf1f6e848063a88b9e0163e82a2912385b0cce369b1c948736fd27',
     'logs/fileFormatIdentification.log': '2942cb39ae7b2c7ff16ae5664876471f5bb3b63735ba9aad397dd824bbf9147f',
     'logs/filenameCleanup.log': '998f76ddcf6729017c0ed914c416edca9ab9ab0a1bfd1449be0ab05cde1aa26d',
     'logs/removedFilesWithNoPremisMetadata.log': 'd7b32d0890f6080adc8006892ae45528576494489937e6b980a2c0121fa9c43f',
     'logs/transfers/fri2-44b8be6a-9d17-419a-9ab5-663d4ddbf4dd/logs/FileUUIDs.log': '4241b089adad4d43d95c46f5cdc79189103352926eb6b8adb4d81efc61779d66',
     'logs/transfers/fri2-44b8be6a-9d17-419a-9ab5-663d4ddbf4dd/logs/FileUUIDsError.log': '682537f7dc819bc415841f6d413efd07d9d610749fac1957e48002a177bd9dde',
     'logs/transfers/fri2-44b8be6a-9d17-419a-9ab5-663d4ddbf4dd/logs/clamAVScan.txt': '6e9b868b92368da3686970e8bf8bf134f274b15e06875e4292e8e399547f68f9',
     'logs/transfers/fri2-44b8be6a-9d17-419a-9ab5-663d4ddbf4dd/logs/fileFormatIdentification.log': '80eb630e7e8de240a608d4b6e7ef57d69fb68e09f706d29e821e3bf77807963a',
     'logs/transfers/fri2-44b8be6a-9d17-419a-9ab5-663d4ddbf4dd/logs/filenameCleanup.log': '3089948b8134eeae82e3694a821367d49559f870f986d8232d25648477d13ba5',
     'objects/Landing_zone-4824250c-8c31-4307-94c1-ab3df0bb10c5.tif': 'cba2171fb10e5732e190a721b0b5020ddd367578a27f0997ebea5303b69eb7ca',
     'objects/Landing_zone.jpg': 'a469c730e705d757d66f53f38bb4455e89d5691a3d87fc7bc069b91fa2a50d46',
     'objects/MARBLES-4e18d821-858a-4c02-aaaa-a5b6cb19977e.tif': '34dd2bfde753e725af9faf4e87362a1c789a81d630eeffa4c7f68ac019e83bef',
     'objects/MARBLES.TGA': '91a5ddca3637590c2ddb50da5feb73ff0b8a98cd09a98afb79adc2cf70bc6220',
     'objects/metadata/transfers/fri2-3bfc2b1b-245b-4433-b397-c01694ebccb4/directory_tree.txt': 'd29334873ec0f79e49e6dd1792f03d68cc217200dcd08a9bf67089b9820d7888',
     'objects/submissionDocumentation/METS.d4a6c7b3-831a-4885-a031-b675d7f7a630.xml': '29cbb88aad308fea56861ea4a056f84f1e46fb224da694abaafb03003ffb5fe0',
     'objects/submissionDocumentation/transfer-fri2-3bfc2b1b-245b-4433-b397-c01694ebccb4/METS.xml': 'e498e4f68aa5ceae0012b422003fa76b838bb75c2b63e4d02d6b0ae9df2fe83d',
     'thumbnails/261c2a5c-6401-40dc-9a37-8feed1b42235.jpg': '0f59f6f50de440b7b36fcd37b4838f9b66571120d6a069fbf4c1cb8cdb43d4b0',
     'thumbnails/4e8fb6ef-311f-41a1-b366-691a9311a38d.jpg': 'd10411bbf097588e1b75d33649cf5e7c1817cda00794fe9edacf566c4775c948'}

**Comment by sevein** [comment]
I've confirmed that https://github.com/artefactual/archivematica/pull/1152 solves this problem.
