### ISSUE TITLE
Problem: AM17 repo contains unexpected contents

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1070]
Should these be removed?
- [x] https://packages.archivematica.org/1.7.x/centos-extras-unsigned/
- [x] https://packages.archivematica.org/1.7.x/centos-extras.apha/ (is this a typo?)
- [x] https://packages.archivematica.org/1.7.x/ubuntu-externals.alpha/
- [x] AM1.6 and SS0.10 packages from https://packages.archivematica.org/1.7.x/ubuntu/
- [x] Old versions of packages from https://packages.archivematica.org/1.7.x/centos-extras/?
- [x] Old versions of packages from https://packages.archivematica.org/1.7.x/ubuntu-externals/?
- [ ] https://packages.archivematica.org/1.7.x/centos/ contains AM17RC4 and SS011RC7 packages that Santi added after my request, should they be removed before the release?

This list may have to be changed, these are just my suggestions.

**Comment by scollazo** [comment]
- Removed centos-extra-unsigned, centros-extras.apha and ubuntu-externals.alpha.
- Executed `reprepro clearvanished` in the ubuntu-externals repo, that got rid of old packages not listed in the repo index.
- Removed ubuntu/[pool,db,dists], those folders will be recreated the next time we add a package with reprepro
- Removed siegfried-[1.5.0,1.6.7,1.7.6] , fido-1.3.4-84, fits-0.10.1-[1,2] , mediaconch-16.08 , libzen-0.4.33, libmediainfo-0.7.88 from centos-extra package.

There is a backup that we can delete after the 1.7 release

**Comment by jhsimpson** [comment]
I went through and verified, looks good closing this issue.
