### ISSUE TITLE
Problem: gunicorn is outdated

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1071]
Released two hours ago. Includes many fixes.

**Comment by ross-spencer** [comment]
Hi @sevein, 

> Includes many fixes.

What fixes do you identify would benefit the project?

**Comment by sevein** [comment]
https://github.com/benoitc/gunicorn/releases/tag/19.8.0

**Comment by sevein** [comment]
Gunicorn is the WSGI server that we use in Archivematica. It's not a library imported by our code but an application server that runs our code. This component is critical in our deployments and any improvement or fix added to Gunicorn should be considered.
