### ISSUE TITLE
Reingesting DSpace AIPs errors at Generate METS

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1083]
#### How to reproduce

1. Create DSpace transfer, e.g. ITEM@2429-2701 from sampledata
2. Full re-ingest

#### Results

![image](https://user-images.githubusercontent.com/606459/39895732-94015224-54ab-11e8-989e-4e366fe6c780.png)

![image](https://user-images.githubusercontent.com/606459/39895740-975f84a4-54ab-11e8-9104-81023f9c734b.png)

**Comment by sromkey** [comment]
We've moved this to verified because it technically fixes the problem but it's still not advisable to reingest a DSpace AIP, because of the issues with the resulting METS.
