### ISSUE TITLE
Problem: Seemingly a recursion error accessing Dataverse repository

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#1085]
While a beta feature, with the current deployment of Dataverse, connected to the storage service, we see the following in Archivematica (before rebasing to `1.7.x`).

![image](https://user-images.githubusercontent.com/1880412/39923687-0197ef22-5525-11e8-8608-d456ba616fff.png)

Related, if we setup `qa/0.x` naively to use a Dataverse transfer source, we do have access to the Dataverse itself, but we are unable to parse the study names:

![image](https://user-images.githubusercontent.com/1880412/39923741-2dc16344-5525-11e8-8149-aefbd3497be2.png)

**Comment by jrwdunham** [comment]
> Related, if we setup qa/0.x naively to use a Dataverse transfer source, we do have access to the Dataverse itself, but we are unable to parse the study names:

@ross-spencer isn't the cause of the ^ simply that the following is not in the AM branch you're testing with?: https://github.com/artefactual/archivematica/blob/dev/issue-1119-cherrypick-dataverse/src/dashboard/src/components/filesystem_ajax/views.py#L86-L87

**Comment by joel-simpson** [comment]
Have tested this in the dataverse QA environment and there is no recursion anymore, and as an added bonus we can see the files within each dataset (i also verified with several datasets that all the files you see in dataverse UI are present in the AM UI).
