### ISSUE TITLE
Problem: job resume after normalization file identification tool selected fails

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1090]
This is reproducible in qa/1.x.

The task page is blank so no more details are reported here.

This was probably caused by https://github.com/artefactual/archivematica/pull/948 or one of the follow-ups (the fix for #980 maybe?).

**Comment by sevein** [comment]
This could be fixed I believe by adding a new ExitCode in the workflow data associating the `0` value to the success job status. This is probably what's missing in the original migration done in #948.

An alternative is to do some changes in the code so the task can suggest the status when the exit code entry is missing in the workflow data.

**Comment by joel-simpson** [comment]
Doing some testing in qa/1.x today and seeing this fail every time. It does appear to only be a display issue -- the correct workflow decision is being made, it is showing a failed status in the dashboard.
