### ISSUE TITLE
Problem: Manual selection of an AIP Storage Location breaks when capture output is false

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#1095]
There is a new feature introduced in #1078 that allows an Archivematica administrator to disable output capture in MCP Client scripts.  This prevents all client scripts from passing anything to the mcp server via std out.

When a SIP is being processed and there is no aip storage location automatically selected (via a processingMCP.xml or via a selection in the processing configuration section of the admin tab of the dashboard) then the user is supposed to be presented with a list of possible aip storage locations.  This list is generated by executing a client script called getAipStorageLocations.py.  This script calls the storage service, gets the list of possible aip storage locations and passes this to the MCP Server via std out.

When output capture is disabled, the MCP Server does not receive the scripts output.  An empty string is written to the database.  When the dashboard attempts to create the drop down list for a user to select from, an error appears in the MCP Server log:

`INFO      2018-05-17 19:57:10  archivematica.mcp.server:jobChainLink:__init__:90:  Running Retrieve AIP Storage Locations (unit 21bf21f3-0c05-4b69-a367-8de836d14469)
INFO      2018-05-17 19:57:10  archivematica.mcp.server:taskStandard:performTask:74:  Executing getAipStorageLocations_v0.0 {'arguments': '', 'createdDate': '2018-05-17 19:57:10.8
87177+00:00'}
ERROR     2018-05-17 19:57:11  archivematica.mcp.server:linkTaskManagerGetMicroserviceGeneratedListInStdOut:taskCompletedCallBackFunction:85:  Unable to create dic from output 
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPServer/lib/linkTaskManagerGetMicroserviceGeneratedListInStdOut.py", line 83, in taskCompletedCallBackFunction
    choices = ChoicesDict.fromstring(task.results["stdOut"])
  File "/usr/lib/archivematica/archivematicaCommon/dicts.py", line 240, in fromstring
    return ChoicesDict(ast.literal_eval(s))
  File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
   ^
SyntaxError: unexpected EOF while parsing
INFO      2018-05-17 19:57:11  archivematica.mcp.server:jobChainLink:__init__:90:  Running Store AIP location (unit 21bf21f3-0c05-4b69-a367-8de836d14469)
DEBUG     2018-05-17 19:57:11  archivematica.mcp.server:linkTaskManagerGetUserChoiceFromMicroserviceGeneratedList:__init__:51:  {} is ChoicesDict: True
INFO      2018-05-17 19:57:11  archivematica.mcp.server:linkTaskManagerGetUserChoiceFromMicroserviceGeneratedList:__init__:69:  Choices: []`

**Comment by sevein** [comment]
https://github.com/artefactual/archivematica/pull/1096 is not in qa/1.x yet (CC @jrwdunham)

**Comment by sevein** [comment]
> #1096 is not in qa/1.x yet (CC @jrwdunham)

In qa/1.x, we're doing this differently (see https://github.com/artefactual/archivematica/issues/938).
