### ISSUE TITLE
Problem: workflow labels can't be translated

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1101]
This feature is not being included in Archivematica 1.8. But it may still show up in the AM18 waffle board because some of the refactoring needed in advance was included in AM18: see #1235, #1238 and #1239.

---

Archivematica 1.7 included user interface translation support (see #506). This work did not include the interface strings found in [Archivematica's workflows](https://wiki.archivematica.org/MCP) because they are in the application database making very difficult to model a translatable schema and push changes via database migrations.

It was decided that the workflow data should be removed from the application database. There was an early attempt in #576 that we are planning to revive.

Action items:

- [x] (PR https://github.com/artefactual/archivematica/pull/1235) **Pass `link_id` to front-end.** This is so our JavaScript code can continue doing conditional representation of micro-services when the labels are translated by using their UUIDs instead.
- [x] (PR https://github.com/artefactual/archivematica/pull/1239) **Refactor processing configuration page.** We want to have the Django form behind this page updated so it does not interact with the workflow models and the processing configuration - this functionality should be moved to MCPServer and exposed via the RPC interface where further work is going to manage workflows using the JSON-encoded document.
- [x] (PR https://github.com/artefactual/archivematica/pull/1238) **Update API's approve_transfer**. Its view uses workflow models, it should be updated and talk to MCPServer's RPC interface as needed.
- [x] (PR https://github.com/artefactual/archivematica/pull/1251) **Creation of workflow module**. So we can load our JSON-encoded workflow document. Update MCPServer to make use of it. Use translated labels in RPC's job_awaiting_for_approval method (used in `ingest_status` and `transfer_status` views). Also: remove workflow models. This will require a new migration that removes the tables and the removal of our fixture imported using `loaddata`. Processing models `UnitVariable` or `Job` need to be updated so foreign keys are updated by `UUIDField`. `json_links` and `graph_links` will stop working therefore they need to be removed.

For future releases:
- **Workflow schema improvements**. See https://gist.github.com/sevein/63e751acd37bde5590d680344ad8b3d5 for more details.
- **New workflow visualization and editor tool**. We need to provide the same functionality offered by `graph_links` until now. We also have to make sure that editing the workflow is still possible as it was before via database migrations. Work in progress: https://github.com/sevein/amflow.

Other improvements that were included in #576 like the gRPC server, removal of the `/mcp` endpoints or the thread-safe `UnitChoices` dict have been excluded this time.

Redmine: https://projects.artefactual.com/issues/12352.

**Comment by sallain** [comment]
This looks so great :heart_eyes:
