### ISSUE TITLE
Problem: inconsistent name for elasticsearch environment var

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#1125]
In [dashboard](https://github.com/artefactual/archivematica/blame/stable/1.7.x/src/dashboard/install/README.md#L126) we use ```ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER```, while in [mcp-client](https://github.com/artefactual/archivematica/blame/stable/1.7.x/src/MCPClient/install/README.md#L137) the variable is called ```ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER```. 

The same happens with ```ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_TIMEOUT``` and ```ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCTIMEOUT```

For consistency, we should use the same name in both places

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#99
