### ISSUE TITLE
Problem: email settings are not configurable

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1128]
Sender e-mail addresses such as [this](https://github.com/artefactual/archivematica/blob/4223fdc545758a778168128ce7b0f767c3735aef/src/MCPClient/lib/clientScripts/emailFailReport.py#L199) should be configurable, to be able to adapt to the organization's IT policy where the application is used.

**Comment by joel-simpson** [comment]
I tested this on a local docker installation using qa/1.x built on 27 July 2018. 
I used the https://mailtrap.io/ service, which allows for minimal email configuration or security protocols (so I didn't have to worry about certificates etc. using SSL and TLS). 

Steps followed: 
- deployed latest qa/1.x from [am.git using docker-compose](https://github.com/artefactual-labs/am/tree/master/compose)
- set up an account with mailtrap.io, which then gives you the account details necessary below
- Added the following environment variables to my local [docker-compose.yml](https://github.com/artefactual-labs/am/blob/master/compose/docker-compose.yml) file:
ARCHIVEMATICA_MCPCLIENT_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST: "smtp.mailtrap.io"
ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST_USER: "...username from mailtrap.."
ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST_PASSWORD: "..password from mailtrap.."
ARCHIVEMATICA_MCPCLIENT_EMAIL_PORT: "2525"
ARCHIVEMATICA_MCPCLIENT_EMAIL_USE_TLS: "no"
ARCHIVEMATICA_MCPCLIENT_EMAIL_USE_SSL: "no"
ARCHIVEMATICA_MCPCLIENT_DEFAULT_FROM_EMAIL: "Archivematica@rdss.com"
- then rebuild the MCPClient container and restart all my services

My new 'custom" email service is now configured. To generate an email, I use /Archivematica-sampletransfers/TestTransfers/fixityCheckShouldFail
This transfer fails the Verify transfer checksums microservice, which triggers the Failed Transfer microservice and sends a failure report by email.
I was able to then see that email in my Mailtrap.io inbox and confirm that it was sent by Archivematica@rdss.com 

Works as expected, so I am moving this to 'verified'. This will need to be tested in more production like environments with other deployment methods (e.g. by package or ansible) before our final release.

**Comment by sallain** [comment]
@sevein does this need documentation?

**Comment by sevein** [comment]
Yes, it does. Do you want me to submit a PR with some preliminary work, then maybe you can polish and complete?

**Comment by sallain** [comment]
That would be wonderful!

**Comment by sevein** [comment]
@sallain, here's a draft for the docs:

```rst
Archivematica's MCPClient sends two types of email reports to all registered
users in the pipeline:

- Normalization reports are sent when the normalization process has found at
  least one error.

- Email fail reports are sent when the workflow failed unexpectedly.

If you are running some kind of QA environment, it is possible that your only
registered user is ``demo@example.com``. Be aware that Archiveamtica ignores
that address from the recipient list - if you want to test the email reporting
functionality make sure that the address is different.

Currently, emails are only sent by MCPClient. This means that in order to
configure the email backend settings, changes are only needed in the MCPClient
service configuration. There are extensive details in the `MCPClient
configuration docs`_.

For example, use the following environment strings to send emails via a local
MTA like Postfix::

    ARCHIVEMATICA_MCPCLIENT_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
    ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST=127.0.0.1
    ARCHIVEMATICA_MCPCLIENT_EMAIL_PORT=25

Archivematica sends emails using the Django Web Framework. You can install
third-party packages like ``django-ses`` supporting additional email backends.
Packages need to be installed in the Python environment of MCPClient.

.. _MCPClient configuration docs: https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/install/README.md
```

**Comment by sallain** [comment]
Documented and added to release notes.
