### ISSUE TITLE
Problem: metadata reingest fails when dc:type is null

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1132]
Original issue @ JiscRDSS: https://github.com/JiscRDSS/archivematica/issues/49.
Pull request @ JiscRDSS: https://github.com/JiscRDSS/archivematica/pull/52.

**Comment by joel-simpson** [comment]
Testing of this issue is blocked by https://github.com/archivematica/Issues/issues/42

**Comment by peterVG** [comment]
Issue https://github.com/archivematica/Issues/issues/42 is resolved so testing of this issue #1132 is now possible. I created a SIP with a metadata.csv that had a null value for dc.type (as per https://github.com/JiscRDSS/archivematica/issues/49#issuecomment-352666192). This completed successfully and an AIP with a <dc:type /> value was created. This AIP then successfully went through an AIP metadata-only re-ingest. This created another dmdSec with update metadata and wherein Archivematica populated the <dc:type> value to "Archival Information Package". 

![screen shot 2018-09-28 at 10 21 16](https://user-images.githubusercontent.com/672121/46223897-851a1080-c309-11e8-972b-f90338f3567b.png)
