### ISSUE TITLE
Problem: SS client timeout setting for async API endpoints is missing

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1133]
Storage Service 0.12 brings asynchronous API endpoints. This means that certain API requests that we make are now going to be responded by SS immediately instead of holding until the work is done. With this in place now we need to update our client so it can have different timeouts when it comes to synchronous vs asynchronous endpoints. For the former you may still want to wait for hours while for the latter case you wouldn't wait too long, perhaps no more than five seconds.

Pull request @ JiscRDSS: https://github.com/JiscRDSS/archivematica/pull/58.

**Comment by jraddaoui** [comment]
Code changes look great and I've been notified that this has been tested for a while.
