### ISSUE TITLE
Problem: processing of datasets containing no files stalls at the end of the Transfer stage 

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1135]
Original issue @ JiscRDSS: https://github.com/JiscRDSS/rdss-archivematica/issues/76, https://github.com/JiscRDSS/rdss-archivematica/issues/59.
Pull request @ JiscRDSS: https://github.com/JiscRDSS/archivematica/pull/59.

**Comment by joel-simpson** [comment]
This is working as expected. 
To test, I created an empty directory and selected it in the Dashboard to start a transfer.
The Transfer fails Verify Transfer Compliance. 
![screenshot from 2018-07-25 19-09-49](https://user-images.githubusercontent.com/17187309/43232351-67512b0e-903e-11e8-861a-fe0ee47487f4.png)

And an error is captured in the task details screen
![screenshot from 2018-07-25 19-09-16](https://user-images.githubusercontent.com/17187309/43232365-745cefcc-903e-11e8-9a7b-fa2360ced739.png)

**Comment by ross-spencer** [comment]
This is an interesting one @joel-simpson @sevein. I wonder if Archivematica could do more earlier to prevent the user from having to enter to Verify Transfer Compliance screen to understand the failure?
