### ISSUE TITLE
Problem: processing is aborted after failure in Index AIP

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1136]
Pull request @ JiscRDSS: https://github.com/JiscRDSS/archivematica/pull/61.

**Comment by joel-simpson** [comment]
Adding some background to this problem (JiscRDSS#61 points to documentation that is not available publicly: 

During our scalability testing on the Jisc project, we saw datasets fail the "Index AIP" microservice, particularly where they included a very large number of files. This microservice creates an index using ElasticSearch based on the contexts of the METS file.   If the METS is very large, then the document that ElasticSearch tries to index is too big and ElasticSearch throws an error. 
JiscRDSS#61 fixes this issue by ensuring that the workflow proceeds even if the Index AIP microservice fails. When indexing fails, the AIP can't be found using the Dashboard search functionality, but it is possible (as a workaround) to retrieve the AIP from the storage service.

**Comment by joel-simpson** [comment]
This is working as expected. If the Indexing AIP fails, processing still completes. 
![image](https://user-images.githubusercontent.com/17187309/43232536-6ad40c78-903f-11e8-8f73-709559a4d59b.png)
(this was demonstrated in https://github.com/artefactual/archivematica/issues/1194 as well)
