### ISSUE TITLE
Problem: AM doesn't have a notion of public URL

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1140]
The self-registration process that AM performs against SS (during the installation) is sometimes insufficient because the pipeline details does not include an accessible URL so SS can reach the pipeline.

The request made by `storageService` during the registration is similar to the one produced with the following command:

```
curl -s -d '{
        "uuid": "99354557-9e6e-4918-9fe3-a65b00ecb199",
        "description": "Test pipeline",
        "create_default_locations": true,
    }' \
        -X POST \
        -H "Authorization: ApiKey test:test" \
        -H "Content-Type: application/json" \
            "http://127.0.0.1:8000/api/v2/pipeline/"
```

The `remote_name` value is not used. When unset, SS populates that property after the value found in the `REMOTE_ADDR` HTTP header - this is okay as a fallback but we want AM to learn a new `site_url` setting that the user can set. This value would be used during the self-registration process.

In RDSS, this was solved differently. See https://github.com/JiscRDSS/archivematica-storage-service/pull/22. for more details.

**Comment by sromkey** [comment]
This is connected to https://github.com/artefactual/archivematica/pull/1142 and since the setting is very much there (under Administration, General) I'm calling this verified!

**Comment by sromkey** [comment]
Whoops,  jumped the gun, we still need to document this! Assigning myself.

**Comment by sallain** [comment]
Documented and added to release notes.
