### ISSUE TITLE
Problem: environments of software dependencies are not well defined

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1144]
Archivematica can be installed in Ubuntu 14.04, Ubuntu 16.04 and CentOS 7. These are very different environments and it is hard to achieve consistency when it comes to external dependencies.

Problems around these differences arise all the time, e.g.:

- The version of the packages are sometimes different, e.g.: trusty's rsync v3.1.0 is [problematic](https://github.com/artefactual/archivematica-storage-service/issues/345), xenial's rsync v3.1.1 is what we need.

- The name of the packages are sometimes different, e.g.: trusty's md5deep is what we've been relying on successfully so far, in xenial the equivalent is hashdeep.

- The packages needed are not always provided by the distro or they're not adequate, e.g.: xenial's hashdeep 4.4-2 is insufficient (see https://github.com/artefactual-labs/ansible-archivematica-src/issues/207) - we'd need to backport artful's hashdeep 4.4-4 which fixes a minor issue preventing a client script from working properly.

When we want to make a package available in a particular distro, we publish it into the corresponding Archivematica package repository. This is done in the am-packbuild repo. We maintain repositories for each minor release, e.g. https://packages.archivematica.org/1.6.x/, https://packages.archivematica.org/1.7.x/ and so on. The contents of the repos are manually curated. In some cases, we borrow packages from other repositories and sources. We also ask users to set up external package repositories that we don't control.

For this and other factors like distro updates, I come to the conclusion that the environment and software stack of the applications that Archivematica depends on are not well defined.

**Comment by sevein** [comment]
Can we package software dependencies in portable environments?

Linux containers may be a very good fit for this use case. There are many container solutions being developed though. Docker is very well known. [Singularity](http://singularity.lbl.gov/) seems to be focused on reproducibility and science projects (see also [Singularity-Hub](https://singularity-hub.org/). Container images are single-file based (easy to distribute) and it does not require a container daemon.

Archivematica should probably learn more than one way to run software dependencies but at the very minimum we should provide a saner default where the environments are reproducible and well defined.

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#95
