### ISSUE TITLE
Problem: Generate AIP METS fails for Dataverse SIPs when document empty directories is set in workflow

### ISSUE THREAD

**Issue by joel-simpson** [artefactual/archivematica#1149]
Testing Dataverse datasets, the Generate AIP METS microservice is failing. This has worked with some datasets, but appears to be failing about half the time. 

![screen shot 2018-06-20 at 10 17 53 am](https://user-images.githubusercontent.com/17187309/41664464-c7581274-7473-11e8-9553-9da3bae93d17.png)

The error message produced is: 
![screen shot 2018-06-20 at 10 18 16 am](https://user-images.githubusercontent.com/17187309/41664479-d0b4c3bc-7473-11e8-90a5-26ee3aa9d60b.png)

**Comment by joel-simpson** [comment]
The following datasets from the Archivematica Test Dataverse all complete Trasnfer processing successfully, but fail at the "Generate AIP Mets" microservice: 
[A study of my afternoon drinks](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PPJ6Y)
[A study with restricted data](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/WZTJWN)
[Bala Parental Alienation Study: Canada, United Kingdom, and Australia 1984-2012 [test]](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/UNMEZF)

**Comment by ross-spencer** [comment]
A workaround is to turn-off the configuration option 'Document empty directories' a 1.7 feature that did not exist in 1.6. This is not a default configuration option inside Archivematica and so when it was turned on, the micro-service began to fail for certain datasets. The interface for this micro-service's code has changed between versions and the Dataverse integration needs to be woven into the code as it is at present.

An example AIP created successfully once the service was turned off is here: http://165.227.37.88:62080/archival-storage/21b16625-73ae-497b-ae2e-4951070e91f6/ 

See the section `<structMap>` in the Archivematica docs for more information about this: https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/archival-storage/aip-structure/#directory-structure.

**Comment by peterVG** [comment]
This now passes successfully. 
The following datasets from the Archivematica Test Dataverse had failed at the "Generate AIP Mets" microservice if "Document empty directories" was set to yes:

[A study of my afternoon drinks](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PPJ6Y)
[A study with restricted data](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/WZTJWN)
[Bala Parental Alienation Study: Canada, United Kingdom, and Australia 1984-2012 [test]](https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/UNMEZF)

However, all three of these Dataverse transfers are now passing Generate AIP Mets while "Document empty directories" setting was set to "yes":

![screen shot 2018-10-18 at 11 34 48](https://user-images.githubusercontent.com/672121/47176430-72707700-d2ca-11e8-841f-06abf315c54a.png)
