### ISSUE TITLE
Problem: AIP re-ingest (metadata and partial) fails at "Verify AIP"

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1150]
This issue is being caused by changes brought in by https://github.com/artefactual/archivematica/pull/1012. The new client script at /clientScripts/verify_aip.py is expecting all of the files associated with a SIP in the database to be present in the Bag manifest file. However, during metadata-only and partial re-ingest the Bag manifest created during re-ingest will be missing some of the files whose checksums were documented in the database during transfer. A `KeyError` is raised as a result. 

(Note that the he Storage Service's `finish_reingest` is responsible for merging the re-ingested AIP into the pre-existing AIP and re-creating the Bag.)

**Comment by jrwdunham** [comment]
Note: this needs to be in the next release because metadata-only re-ingest is currently broken in AM 1.7.

**Comment by sevein** [comment]
I tried to port #1152 to stable/1.7.x but there are conflicts. The `verify_aip.py` script in qa/1.x that #1152 modifies is significantly different from stable/1.7.x's `verifyAIP.py`.

My suggestion is to move this issue to the 1.8.0 milestone.

**Comment by sevein** [comment]
Bumping to 1.8.0 as this problem was caused by a change that never made it into the 1.7 branch.
