### ISSUE TITLE
Enhancement: FPR: Add details to format selection list 

### ISSUE THREAD

**Issue by timhutch** [artefactual/archivematica#1156]
There are a few office document formats (to mention the main example I've dealt with) for which the multiple versions make it really difficult to pinpoint the correct format, when adding a new normalization rule, characterization rule, etc. See screenshot for Microsoft Word.

Adding the PRONOM ID, software version, or both, to the selection list for "related format" would make this a lot easier.

There are similar limitations in the list of formats, but at least in that case you can click through to see the exact version.

![format selection](https://user-images.githubusercontent.com/6011059/41734980-be293142-7545-11e8-84b0-a758f9084ac1.png)

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#94
