### ISSUE TITLE
Problem: FPR: Microsoft Word for MS-DOS Document has wrong versions linked

### ISSUE THREAD

**Issue by timhutch** [artefactual/archivematica#1157]
In the default format list, Microsoft Word for MS-DOS Document lists as versions:
- Microsoft Works Word Processor Macintosh 4 (fmt/273)
- MS Access (fmt/275)
- SPSS Output File (fmt/274)

Correct versions would include the corresponding x-fmt entries - x-fmt/273, x-fmt/274, x-fmt/275. These are listed under Microsoft Word.

![microsoft word for ms-dos document](https://user-images.githubusercontent.com/6011059/41735650-74c7d74a-7547-11e8-93b8-a9335305e927.png)

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#93
