### ISSUE TITLE
Problem: ghostscript to-PDF normalization command claims to create PDF/A 1a when in fact it creates PDF/A 1b

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1158]
Our "Transcoding to pdfa with Ghostscript" FPR normalization command says its output format is "Acrobat PDF/A 1a". See `/fpr/fpcommand/d6a33093-85d5-4088-83e1-b7a774a826bd/`. However, that command actually generates "Acrobat PDF/A 1b" derivatives. See [PDF/A 1b on PRONOM](http://www.nationalarchives.gov.uk/pronom/fmt/354) and [PDF/A 1a on PRONOM](http://www.nationalarchives.gov.uk/pronom/fmt/95).

I have verified that we create 1b not 1a with our `gs` command

    gs -dPDFA -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile="%outputDirectory%%prefix%%fileName%%postfix%.pdf" "%fileFullName%"

It sounds like it is actually quite difficult to generate PDF/A 1a from arbitrary textual source files. It has much more stringent requirements than PDF/A 1b. See this forum post where a developer (creator?) of Ghostscript says (in 2009) that he [will not support PDF/A 1a creation because it is too hard, if not impossible in practice](https://ghostscript.com/pipermail/gs-devel/2009-August/008556.html).

Then there's also this document where [we talk about creating PDF/A 1b](https://wiki.archivematica.org/PDF_to_PDF/A_using_Ghostscript.) with that same `gs` FPR command.

My conclusion from all of this is that we probably just need to change our FPR command to be more honest about what its true output format is, viz. "Acrobat PDF/A 1b", i.e., PRONOM fmt/354.

See internal redmine 12265.

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Artefactual (internal)](https://trello.com/c/AxNvL2Bv/11-artefactual-internal)

**Comment by sromkey** [comment]
The output file format in the command Transcoding to pdfa with Ghostscript now correctly reads Acrobat PDF/A 1b.
