### ISSUE TITLE
Problem: orphan client script verifyAIP shouldn't exist

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1159]
[verifyAIP.py](https://github.com/artefactual/archivematica/blob/de1cfbb86bb3da53f1443c0ded6487b477a9a2af/src/MCPClient/lib/clientScripts/verifyAIP.py) should be removed because it was replaced by [verify_aip.py](https://github.com/artefactual/archivematica/blob/de1cfbb86bb3da53f1443c0ded6487b477a9a2af/src/MCPClient/lib/clientScripts/verifyAIP.py) (see 9451abf682987f718266b809d26aeb15ac848e5a).

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#92
