### ISSUE TITLE
Problem: Errors should be more obvious in the user interface

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#1162]
There are lots of examples of this but in particular I'm thinking of situations when a job has failed but the micro-service gives no indication. For example, when a file fails in format identification the Job is red and reads Failed but nothing indicates at the micro-service level, so it may be missed by the user.

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#1

**Comment by sallain** [comment]
connected to artefactual/archivematica#1153

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#97
