### ISSUE TITLE
Enhancement: allow aip reindexing script to be run post-ES upgrade

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#1173]
Related to #1171, once Elasticsearch is upgraded to 6.x users will need to be able to rebuild their AIP index using the new version.

**Comment by jraddaoui** [comment]
There are three commands now available in the Dashboard to rebuild the Elasticsearch indexes:

Rebuild AIPs and AIP files indexes (requires access to the AIPs in the local filesystem):
```
./manage.py rebuild_elasticsearch_aip_index_from_files /var/archivematica/sharedDirectory/www/AIPsStore"
```

Rebuild Transfers and Transfer files indexes (from the database):
```
./manage.py rebuild_transfer_backlog"
```

Rebuild all indexes (from another ES cluster/server using the 1.x version):
```
./manage.py reindex_from_remote_cluster http://192.168.168.196:9200"
```

Check each command help (`-h`) or [their code](https://github.com/artefactual/archivematica/tree/qa/1.x/src/dashboard/src/main/management/commands) for more information on how to run those commands.

**Comment by sromkey** [comment]
We'll need to test this as part of upgrade testing. We should make sure AIPs are in storage and transfers are in backlog pre-update and then rebuild the AIP index/Transfer index after upgrading. Adding @scollazo as an assignee as he can help us coordinate.

**Comment by sallain** [comment]
To do items:
* @jraddaoui to wrap up docs PR 253
* @scollazo to test upgrading a pipeline that has packages in backlog and AIP storage

**Comment by jraddaoui** [comment]
Docs PR is ready for review.
