### ISSUE TITLE
Problem: disabling ES search appears to break post_store_aip_callback and dspace_handle_to_archivesspace

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1174]
See https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/lib/clientScripts/post_store_aip_hook.py#L88-L94. 

It appears that when ES is disabled, then `dspace_handle_to_archivesspace` and `post_store_aip_callback` will never get called. This indicates to me that if ES is disabled, then some workflows will be broken that should not be.

**Comment by jraddaoui** [comment]
Agree. I may be able to tackle this in #1172 if it has not been fixed sooner.

**Comment by jraddaoui** [comment]
To test this, in with the `search_enabled` config set to `false`, after an AIP has been successfully stored, the following workflows should be executed:

- SS file deletion request (when all files have been arranged).
- DuraSpace handle to ArchivesSpace.
- SS post store AIP callback.

**Comment by ablwr** [comment]
I think I have tested this successfully but @jraddaoui we can talk more about it tomorrow :)

**Comment by ablwr** [comment]
@mamedin and I both tested this and it is VERIFIED FIXED!
