### ISSUE TITLE
Problem: two model classes have bugs in their __unicode__ methods

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1180]
The following change is the solution. The bug is not usually encountered, unless you try to print an instance of one of these model classes in the repl:

    --- a/src/dashboard/src/main/models.py
    +++ b/src/dashboard/src/main/models.py
    @@ -930,7 +930,7 @@ class TaskType(models.Model):
             db_table = 'TaskTypes'
     
         def __unicode__(self):
    -        return _('TaskType ID: %(id), desc: %(desc)') % {
    +        return _('TaskType ID: %(id)s, desc: %(desc)s') % {
                 'id': self.id,
                 'desc': self.description
             }
    @@ -948,7 +948,7 @@ class TaskConfig(models.Model):
             db_table = u'TasksConfigs'
     
         def __unicode__(self):
    -        return _('TaskType ID: %(id), desc: %(desc)') % {
    +        return _('TaskType ID: %(id)s, desc: %(desc)s') % {
                 'id': self.id,
                 'desc': self.description
             }

**Comment by sromkey** [comment]
@jrwdunham Could you please describe how to reproduce this issue?

**Comment by sevein** [comment]
This I believe can only be reproduced using a Django shell.

If you're using our Compose environment in am.git:

```
$ make manage-dashboard ARG="shell"
[1] % from main.models import TaskType
[2] % TaskType()
```

[2] raises an exception `ValueError`

    ValueError: unsupported format character ',' (0x2c) at index 18

#1184 fixes that.

**Comment by jrwdunham** [comment]
Yeah, this would never have affected a user, unless we started trying to log `TaskType` instances or something like that.

**Comment by sromkey** [comment]
ok, thanks!
