### ISSUE TITLE
Problem: MCPServer internals can't be monitored

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1187]
Currently we don't have the ability to monitor the internals of MCPServer.
This makes really hard to reason about errors.

This is a good start: https://prometheus.io/docs/practices/instrumentation/.

**Comment by ross-spencer** [comment]
Hi @sevein, outside of logging which we can control and monitor quite easily, I'm not sure what internals means in this issue?

**Comment by sevein** [comment]
We're thinking on details that are not necessarily actionable, e.g. we have pools of threads so how long do threads take to complete work (histogram), how often they error (counter), how many items are queued (gauge)...

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/onaPPfEg/3-jisc-rdss)

**Comment by sevein** [comment]
#1206 added some basic instrumentation exposed via a HTTP server. The server is enabled only when `ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_HTTP_SERVER` is defined. cURL can be used to query the server and retrieve the samples. In a normal setup, the user would run Prometheus to collect the samples and some other tools for graphing, alerting, etc...

**Comment by jraddaoui** [comment]
Hi @mamedin, passing this to you as you have some experience with Prometheus/Grafana.

**Comment by mamedin** [comment]
The #1206 has been used and tested with a Prometheus-Grafana instrumentation solution in JISC/RDSS 3 months ago: https://github.com/JiscRDSS/rdss-archivematica/commit/5f685ccd64645c089e103adc5c781006a20fcb8c

I tested again adding the line to the /etc/default/archivematica-mcp-server file:
```
ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_HTTP_SERVER=127.0.0.1:12345
```
Restarting mcp-server and checking the new prometheus http server:

```
wget 51.38.224.179:12345
```
I got the file:
```ubuntu@mamedin-bionic:~$ cat index.html 
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2752106496.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 59232256.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1539363847.91
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2.44
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 11.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="2",minor="7",patchlevel="15rc1",version="2.7.15rc1"} 1.0
# HELP task_group_runner_active_units Number of units currently being processed
# TYPE task_group_runner_active_units gauge
task_group_runner_active_units 0.0
```
This is the expected behaviour :+1:
