### ISSUE TITLE
Problem: can't set custom premis agent version number in qa or dev environments

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#1192]
When deploying Archivematica from the qa/1.x branch, the version number is currently set to `1.7.0` - which is not accurate.  No version number is technically accurate, since the code in qa/1.x has not been officially release yet.

The version number is set in more than one place - in the UI it is populated from version.py in archivematicaCommon, in the METS files inside AIP's, the premis agent for archivematica has an identifiervalue that is read out of the database.

At a minimum, there should be a way to override the database value for the archivematica premis agent, so that aip's produced by a qa system are mistakenly marked as being made by production code.   It would be better to be able to set this value at buildtime/deploytime, rather than have to add a new django migration for each change.

Changing the version number in the UI would be nice, but is much less important,.

This is important for users like JiscRDSS - who are planning on deploying a production system from a qa branch of archivematica.

**Comment by sevein** [comment]
Related:
- https://github.com/artefactual/archivematica/issues/658
- https://github.com/artefactual/archivematica/issues/1183

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/onaPPfEg/3-jisc-rdss)

**Comment by peterVG** [comment]
I'm not clear on how to test for this?

**Comment by jraddaoui** [comment]
Executed:
```
docker-compose run \
        --rm \
        --entrypoint /src/dashboard/src/manage.py \
            archivematica-dashboard \
                set_agent_code v1.8.0-rc1
```

Created an AIP and found the following PREMIS agent in the METS and pointer files:
```
<premis:agent xmlns:premis="info:lc/xmlns/premis-v2" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-2.xsd" version="2.2">
    <premis:agentIdentifier>
        <premis:agentIdentifierType>preservation system</premis:agentIdentifierType>
        <premis:agentIdentifierValue>v1.8.0-rc1</premis:agentIdentifierValue>
    </premis:agentIdentifier>
    <premis:agentName>Archivematica</premis:agentName>
    <premis:agentType>software</premis:agentType>
</premis:agent>
```

It also appears as the agent code in `.../administration/version/`.
