### ISSUE TITLE
Problem: can't add tests to MCPServer

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#1195]
I tried to write a couple of unit tests for functions that belong to MCPServer but I couldn't get Travis to pass even though they were passing in my local env successfully.

It's also hard to run tests because of the way we run code at the import level so imports have side effects that you don't want from a test, like blocking forever.

Here's the patch:
https://gist.github.com/sevein/631e8e0847eec97a2bbda795b19d82f0 - needs some more work.

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#88
