### ISSUE TITLE
Enhancement: "Completed successfully" appears even when Transfer Fails

### ISSUE THREAD

**Issue by rogerlayton** [artefactual/archivematica#1203]
I reject a Transfer, and it completes successfully, and it shows this message.

However, for this action I would prefer to this and indication that the entire Transfer did not complete successfully even though the MicroService did reach completion.

**Comment by sromkey** [comment]
Hi @rogerlayton ! Thanks for submitting some issues. Just a couple of days after you filed them we coincidentally started using a new repo for issues- https://github.com/archivematica/issues . Do you mind if I move the issues you filed there, so that we don't lose track of these ideas?

**Comment by sallain** [comment]
This issue was moved to archivematica/Issues#87
