### ISSUE TITLE
 Process transfer JSON metadata fails when one of the values in a multi-valued field is an integer

### ISSUE THREAD

**Issue by photomedia** [artefactual/archivematica#1766]
**What version of Archivematica and the Storage Service are you using?**
1.12.1

**What did you do to cause this bug to happen?**
Attempt to ingest a metadata.json file that includes an integer as one of the field values in a multi-value field.

**What did you expect to happen?**
I expected for the metadata.json file to be successfully converted to CSV for ingest.  

**What did you see instead?**

Failure on the following step: Job Process transfer JSON metadata  

**Can you reproduce this reliably?**

Yes.  Whenever there is a JSON field with multiple values, and one of the values is an integer, this error shows up.
For example:

```
[ {
    "dc.relation": [
      "https:\/\/someurl.ca\/99",
      "some other identifier",
       824675433
    ]
  }]
```

**If a specific Job is failing, what output did it produce? This is available by clicking on the gear icon.**

I see the following error:

'int' object has no attribute 'encode'Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/json_metadata_to_csv.py", line 153, in call
    job.set_status(main(job, sip_uuid, json_metadata))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/json_metadata_to_csv.py", line 138, in main
    writer.writerow(object_to_row(fix_encoding(row), headers))
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/json_metadata_to_csv.py", line 85, in fix_encoding
    return {key.encode("utf-8"): encode_item(value) for key, value in row.items()}
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/json_metadata_to_csv.py", line 85, in <dictcomp>
    return {key.encode("utf-8"): encode_item(value) for key, value in row.items()}
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/json_metadata_to_csv.py", line 74, in encode_item
    return [i.encode("utf-8") if i else "" for i in item]
AttributeError: 'int' object has no attribute 'encode'

**COMMENTS:**
I believe the following line makes the assumption that if there are multiple items, in a field, they are all convertible to string using encode("utf-8"), but this doesn't work if one of the items is a number (integer):

https://github.com/artefactual/archivematica/blob/7ebfb2b716b7ba3bfd49528f73b7fffa2d677207/src/MCPClient/lib/clientScripts/json_metadata_to_csv.py#L74

**Comment by sromkey** [comment]
Hi @photomedia - we no longer track issues in this repo. Could you please file it here instead? https://github.com/archivematica/Issues/issues

**Comment by photomedia** [comment]
apologies, and here I thought "wow, they closed all the issues! :)  "   I'll remember next time!  
I posted it here: https://github.com/archivematica/Issues/issues/1462
