### ISSUE TITLE
Elasticsearch version is outdated

### ISSUE THREAD

**Issue by sebastienmuller57** [artefactual/archivematica#1807]
Hello,
Archivematica 1.13.2 is using an outdated version of Elasticsearch (version 6). Is it scheduled to update the product with a recent version of Elasticsearch  ?

**Comment by sromkey** [comment]
Hi there- we track Archivematica issues in a different Github repo- here is the link for the relevant one regarding the Elasticsearch upgrade: https://github.com/archivematica/Issues/issues/1548
