### ISSUE TITLE
Problem: Archivematica uses sudo

### ISSUE THREAD

**Issue by hakamine** [artefactual/archivematica#567]
Some parts of archivematica, like [this client script](https://github.com/artefactual/archivematica/blob/stable/1.5.x/src/MCPClient/lib/clientScripts/setDirectoryPermissionsForAppraisal.sh), use commands with sudo. Is this really necessary? Isn't it enough with having directories to which archivematica need full read/write access (like the sharedDirectory) set to owner archivematica? 
The archivematica installer sets limited sudo for the user archivematica. This has security implications and may not be allowed depending on the IT policy of the organization. If sudo is not required, archivematica should be refactored to not use it.

**Comment by sevein** [comment]
Related: https://github.com/artefactual/archivematica/issues/567.

**Comment by sevein** [comment]
Related: https://github.com/artefactual-labs/am-packbuild/issues/37.

**Comment by sevein** [comment]
Fixed in 4d979ecb283b7129b905a236fea65bda276b2743 (part of #682).

**Comment by sallain** [comment]
@sevein Is there anywhere in the documentation that commands need to be changed?

**Comment by sevein** [comment]
I don't think so, it was an internal change only.

**Comment by kellyannewithane** [comment]
Reference in admin manual - permissions needed - installation
