### ISSUE TITLE
Problem: deprecated setup scripts still in place

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#586]
I think there are not needed anymore and should be deleted:

- `/dev-helper`
- `/dev-installer`
- `/localDevSetup`
- `/src/MCPServer/share/*` (`sharedDirectoryStructure` is still necessary)

**Comment by sevein** [comment]
Fixed in #603.

**Comment by kellyannewithane** [comment]
@jrwdunham Update developer documentation in the wiki

**Comment by sromkey** [comment]
@jrwdunham could you take a look and confirm this is verified?

**Comment by jrwdunham** [comment]
@sromkey @kellyannewithane @sevein I searched through the wiki and the qa/1.7.x codebase and found no references to the files deleted in resolving this issue. There are references to some of this stuff in https://wiki.archivematica.org/Development_environment, but that is already clearly deprecated. The https://wiki.archivematica.org/Getting_started page does not appear to reference any of the files deleted here. I think we can move this to Done in the AM 1.7 project.
