### ISSUE TITLE
MCPServer unrequired osdeps

### ISSUE THREAD

**Issue by hakamine** [artefactual/archivematica#590]
The following osdeps listed in https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/MCPServer/osdeps/Ubuntu-14.json  may not be required:

- dbconfig-common
- logapp
- uuid

**Comment by jhsimpson** [comment]
#614 resolved this issue, that has been merged, so I am closing this issue.

**Comment by sromkey** [comment]
@hakamine can you please confirm that this issue is verified?

**Comment by hakamine** [comment]
Confirmed, those MCPServer osdeps are not in qa/1.x or stable/1.7.x
