### ISSUE TITLE
Problem: client script reads from MCPServer config

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#596]
The case is very subtle. 

There are a number of client scripts that import dicts.py (from archivematicaCommon) which reads from serverConfig.conf.

So if you deployed MCPClient you had to provision the serverConfig.conf file too.

**Comment by sevein** [comment]
Fixed in #670.

**Comment by sromkey** [comment]
@sevein can you describe how this can be QA'd?

**Comment by sevein** [comment]
This is something that we've verified indirectly by having MCPClient containers completely isolated without access to the config of MCPServer. JiscRDSS uses this and our am.git/compose env too. I would say this is verified.
