### ISSUE TITLE
Problem: quarantine delay is not reliable

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#598]
When a transfer is sent to quarantine the user will be prompted to remove it from quarantine manually. But also, by default, the transfer is removed from quarantined automatically after 28 days. This is a delay that can be configured by the user in the processing configuration.

The purpose of the delay is to allow virus definitions to update, before virus scan.

There are two modules in MCP implementing the processing delay ([1](https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/MCPServer/lib/linkTaskManagerChoice.py#L97-L121), [2](https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/MCPServer/lib/linkTaskManagerReplacementDicFromChoice.py#L87-L116)).

It's done with a timer from the threading module which doesn't seem to be provide real guarantees. What would happen if the process is interrupted before the timer finishes?
AMQP or Redis seem to offer primitives that allow implementing scheduling. Gearman doesn't seem to provide any.

### Solution 1

Deprecate quarantine delay functionality. Only the user would be able to remove it from quarantine.

### Solution 2

Update virus definitions before antivirus checking?

### Solution 3

Implement delayed jobs using Redis or similar. Once a new scheduled job comes in, MCP would persist it somewhere. In a loop, the tasks would be polled frequently and throw new jobs when needed. The following is a library that could be used for this purpose or as a reference: https://github.com/josiahcarlson/rpqueue/ (it uses Python + Redis).

Remember that Redis is already used as a Gearman backend, we've tried this successfully in our local Docker developer setup. Adding Redis to our stack would be also beneficial for other purposes like caching in Django.

**Comment by jhsimpson** [comment]
I prefer deprecating the quarantine functionality altogther (i.e. remove the microservice).  This requires more discussion, @sallain @kellyannewithane and others.  

Quarantine is a feature that was created before there was an aip reingest workflow, or a transfer backlog.

It is possible to put transfers into backlog and do a full reingest later, which achieves the same purpose as quarantine.  The quarantine storage space is not managed by the storage service, and is not being monitored, so it is not a good place to store content for any length of time.

**Comment by sromkey** [comment]
Justin's comment:
"It is possible to put transfers into backlog and do a full reingest later, which achieves the same purpose as quarantine."
I don't really agree with this statement- quarantine is meant to prevent ingesting viruses into your archival storage to begin with, at least I think it is. Being able to re-ingest the AIP means the virus is potentially in storage for some period of time. We're also not offering up any kind of alert that there might be a virus so how would users know which AIPs to reingest and rescan for viruses?
I'm under the impression though that virus definitions are updated very frequently, daily I think? So perhaps we could still depreciate the delay without much risk. It's an extremely unusual use case to be ingesting materials that were literally created the same day.

**Comment by jhsimpson** [comment]
If you use the quarantine feature then your content is moved into a special folder within the processing location before virus scanning happens.  If the files have viruses you have no way of knowing, until you pull the content out of quarantine and process it.

If you move a transfer to backlog, then there will be a record of a virus scan event - if viruses were found, you would be alerted, and you wouldn't be able to move the content to transfer backlog, the transfer would fail.  If no viruses are found, you can move the content to transfer backlog.   

We know that files over a certain size cannot currently be scanned.  And it is possible that new virus definitions might catch viruses that were not caught in the original scan. So there is no way to deliberately store files that are known to have viruses into your transfer backlog or archival storage locations, but there is an at least potential use case for why you might want to scan again at some future point.  

With the current quarantine feature, you can store content that has not been virus scanned at all, so using that feature allows you to store files that potentially have undetected viruses in them.  

I think we are converging on a general agreement though, that we could remove the quarantine workflow without really removing functionality.

**Comment by sevein** [comment]
Removing nodes from the workflow graph became easier in its JSON-encoded forms. As it turns out, getting rid of quarantine is very easy too. The main advantage is being able to delete some ugly and it makes the workflow ~8% smaller (39 nodes are removed incl. chains, links and watched directories).

Here's the branch: https://github.com/artefactual/archivematica/compare/qa/1.x...dev/issue-598-remove-quarantine?expand=1.

I'm guessing this would also fix the following issue: https://github.com/archivematica/Issues/issues/426.

If we'd be removing quarantine, the following repos would need to be updated too:
- https://github.com/artefactual/archivematica-docs
- https://github.com/artefactual-labs/archivematica-acceptance-tests

**Comment by ross-spencer** [comment]
I agree archivematica/Issues#426 would be fixed. I don't know if this has been raised, so credit to the person that did if so, but this sounds like a case for an ADR cc. @sromkey 

If that was agreed upon, then perhaps we could:

a) write the ADR now, and provide the users the length of the release to decide upon it, and merge at the end
b) write the ADR now, and then merge in 1.11. 

The ADR might cover:

* Our impression of the state of virus checking today.
* The impact that has on the types of collections being transferred.
* Tools that users have to be confident in their collection, e.g. a file with a checksum that hasn't changed since some date in the past won't have a new 'virus-baring payload'. May also have been picked up through internal virus scanning. ClamAV in Archivematica is like a last belt-and-braces check, 
* Indication as to where vulnerabilities might actually lie, e.g. not upgrading software and its dependencies, and so forth. 
* Anything else?

What do you think?

**Comment by sallain** [comment]
Just a note here that quarantine delay doesn't actually seem to work at all, at least on 1.10.

**Comment by ross-spencer** [comment]
**NB.** [Proposed ADR](https://github.com/archivematica/archivematica-architectural-decisions/blob/master/0008-remove-quarantine.md).

**Comment by sromkey** [comment]
In light of the ADR I'm going to milestone this issue for 1.11 and put it in Review. The review should check whether or not quarantine has been removed and if that's had any unexpected impact on the workflow.

**Comment by sevein** [comment]
Support for quarantine had been removed from the workflow engine, but we still have to delete references from processing configuration and the workflow definition if that makes sense.

**Comment by sromkey** [comment]
> Support for quarantine had been removed from the workflow engine, but we still have to delete references from processing configuration and the workflow definition if that makes sense.

Should we open a new issue or should this one be in Ready?

**Comment by sevein** [comment]
This one in Ready would work for me!

**Comment by replaceafill** [comment]
These are the quarantine links that have been removed from the `qa/1.x` workflow ([download full SVG](https://drive.google.com/file/d/1J5K5WOtcTlKVAR8Qo7vfzeFlqqADSCZj/view)):

![qa](https://user-images.githubusercontent.com/560781/71156010-ab74e600-2204-11ea-9ca0-1ab0162fd739.png)

I also marked the four links that are connected to the quarantine feature and the `Scan for viruses (1c2550f1-3fc0-45d8-8bc4-4c06d720283b)` link which is where all the feature links converge.

And this is how the workflow looks now with the quarantine feature removed ([download full SVG](https://drive.google.com/file/d/1B21iZQ3uFFcjP8r0F469uPxytjc1i_CT/view)):

![branch](https://user-images.githubusercontent.com/560781/71157133-01e32400-2207-11ea-8e35-5422bdc2dcaf.png)

Notice how the magenta links have been reconnected.

**Comment by ross-spencer** [comment]
**_Testing notes,_** @replaceafill feel free to edit below my simplification for those looking at this prior to release is that you should see the following new links when you attempt each transfer type. `->` denotes the link from one microservice job to the next:

**All bag transfers:** _Assign UUIDs to directories -> Scan for Viruses_
**Dspace:** _Verify metadata directory checksums -> Scan for Viruses_
**Dataverse and Standard transfer:** _Verify metadata directory checksums -> Scan for Viruses_

**Additional workflows:**

**TRIM (not acively supported):** _Assign UUIDs to directories -> Scan for Viruses_
**Maildir transfer (status unknown):** _No change_

From Archivematica's perspective, once scan for viruses is executed in each of those workflows, processing will continue as before. No other changes appear.

**Comment by sallain** [comment]
All that red is SO BEAUTIFUL

**Comment by ablwr** [comment]
- [x] Zipped bag
- [x] Unzipped bag
- [x] Standard transfer
- [x] Dspace transfer
- [x] Dataverse transfer

Tested on qa/1.x (https://github.com/artefactual/archivematica/commit/baf565e4abc3bcf9480ee0784734ce9b0b223f63, proto-1.11 RC candidate)
