### ISSUE TITLE
Problem: script to erase ES indices is not available anymore

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#605]
[eraseElasticSearchIndexes.py](https://github.com/artefactual/archivematica/blob/stable/1.6.x/localDevSetup/eraseElasticSearchIndexes.py) was deleted in 0ba7f1babdc18d18d572a42e0dc39a1adc559f98 (see #586 to know more). It turns out our Ansible role relied on it when the user requested to flushed the search indices.

Solution:
- Create custom django-admin command
- Use it in [github.com/artefactual-labs/ansible-archivematica-src](https://github.com/artefactual-labs/ansible-archivematica-src/tree/qa/1.7.x) (qa/1.7.x only)

**Comment by scollazo** [comment]
We can also address this from the ansible role. It makes sense to me that elasticsearch indexes (or mysql dbs) creation/deletion tasks can be managed outside of archivematica.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-labs/ansible-archivematica-src/pull/123.

**Comment by kellyannewithane** [comment]
@hakamine  Can you please review this and add any required documentation to the ansible-archivematica-src repo?

**Comment by sallain** [comment]
@hakamine Bumping this - please leave a comment if nothing needs to be done.

**Comment by hakamine** [comment]
It looks like nothing else needs to be done, the role is already fixed (it has tasks to delete ES indices when required), docs don't need changes (it is an internal change)
