### ISSUE TITLE
Problem: Archivematica does not send log events to stderr

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#606]
MCPServer, MCPClient, Dashboard and client scripts... they're all set up with a handler that writes to disk (`/var/log/archivematica`). If we sent to `stderr` instead, the logs would be captured by upstart, journalctl, docker, etc...

Client scripts use sys.stdout and sys.stderr directly but most of them also have a leveled logger defined. That's a lot of streams! I think they all should use the logger which should be set up to send the events to the standard error stream. MCPClient can continue capturing stdout/stderr which is relevant when a client scripts fails, etc...

**Comment by sevein** [comment]
Solved in #682.

**Comment by sallain** [comment]
@sevein can you let me know how to test this?
