### ISSUE TITLE
Problem: clamdscan can't connect to remote clamd server

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#620]
The suggested solution is to modify the [antivirus checking script](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/archivematicaClamscan.py) so it creates a configuration file on the fly as clamdscan does not support environment variables.

1. Create a temporary file, e.g. `/tmp/tmp.Cc0IfaOF2F`
2. Write config values to it (e.g. `TCPSocket 3310` and `TCPAddr clamavd`). The client script looks up the config values in MCPClient.
3. Run `clamdscan --config-file=/tmp/tmp.Cc0IfaOF2F`

**Comment by sevein** [comment]
I'm considering to build our own client based on https://github.com/graingert/python-clamd ( @hakamine suggested me this one). The protocol is simple enough that I feel confident not using the official client. The motivation is to avoid dealing with `clamdscan` - I spent quite a while yesterday trying to set it up and I ran into all kind of issues, from having issues passing `--config-file` if the `/etc` config file had not been removed, an issue with `getaddrinfo` not working when not passing `shell=True` to subprocess, etc...

And all to be said, the approach originally suggested feels like an ugly hack. I tried something along these lines:

```python
@contextmanager
def clamdscan_command():
    command = ['clamdscan']
    addr = mcpclient_settings.CLAMAV_SERVER
    if addr == "":
        yield command
        return
    host, port = addr.split(':')
    with tempfile.NamedTemporaryFile(delete=False) as fp:
        fp.write('TCPAddr {}\n'.format(host))
        fp.write('TCPSocket {}\n'.format(port))
        command.append('--config-file={}'.format(fp.name))
        yield command

with clamdscan_command() as command:
    scan_rc, scan_stdout, scan_stderr = executeOrRun("command", command, printing=False, shell=True)
```

An advantage to talk directly to the server is that you can get the current version of ClamAV running in the server. The existing approach where we execute `clamdscan -V` would only return the local version.

**Comment by sevein** [comment]
a36a9bf

**Comment by sallain** [comment]
@sevein Is successful virus scanning enough to mark this as tested? Or is there something else I need to do?

**Comment by sevein** [comment]
You could have a more complex setup where the antivirus server is only available over the network (this is true in our Compose environment: https://github.com/artefactual-labs/am/tree/master/compose - which you may want to try).

This is the environment variable where we tell MCPClient where to find the antivirus server: https://github.com/artefactual-labs/am/blob/f071c5b2caa0669fff7386bd867f3973454b7a20/compose/docker-compose.yml#L139.

Additionally, we can pass files by reference (instead of streaming the contents) with `ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_PASS_BY_REFERENCE=true`, but this is at the moment an undocumented feature. I wouldn't bother for now.

**Comment by sallain** [comment]
Since we don't officially support Docker yet, I'm not going to test this in that environment; clamdscan seems to be working as expected in Ubuntu and CentOS so will mark as complete for 1.7.
