### ISSUE TITLE
Problem: atom dip upload not working

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#622]
The atom dip upload feature is not working in qa/1.x

Some problems I found:
- When using the web interface, the question "Upload DIP" ->"Upload DIP to Atom" asks for the atom slug, but never finishes and the question is always in "Awaiting decision" state.
- Using am mcp-rpc-cli, when selecting "Upload DIP to Atom" for the "Upload DIP" question, there is a new question, with only one choice ( upload-qubit_v0.0):

`
<choicesAvailableForUnit>
    <UUID>3f857f46-6a10-472d-a564-77bd7534f58b</UUID>
    <unit>
      <type>DIP</type>
      <unitXML>
        <UUID>c8529576-a069-48fc-b056-8e260275e86c</UUID>
        <currentPath>%sharedPath%watchedDirectories/uploadDIP/atom4-c8529576-a069-48fc-b056-8e260275e86c/</currentPath>
      </unitXML>
    </unit>
    <choices>
      <choice>
        <chainAvailable>0</chainAvailable>
        <description>upload-qubit_v0.0</description>
      </choice>
    </choices>
  </choicesAvailableForUnit>
`
- The switch \--rsync-command="None"\ is being passed to the script, and that makes rsync fail with error 14

**Comment by kellyannewithane** [comment]
This appears to be still broken.  Tried storing the AIP first and then the DIP and also tried storing the DIP first.  Either way, after the atom slug is entered the job doesn't finish

**Comment by kellyannewithane** [comment]
Workflow diagrams for StoreAIP and UploadDIP
https://drive.google.com/open?id=1DZ4w2o7gzhEKXiSpRQQQW_b3p5Jl7PeR
https://drive.google.com/open?id=1EdJtls4S_ZhisvmcSBhpd317k2SNUNjb

**Comment by sromkey** [comment]
This is working after recent code changes.
