### ISSUE TITLE
Problem: email report script fails to close email client

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#624]
`emailFailReport.py` calls quit() inside a finally block which is not working if the client could not be instantiated in the first place, e.g. see https://stackoverflow.com/q/984526.

```
File "/src/MCPClient/lib/clientScripts/emailFailReport.py", line 75, in send_email
    server.quit()
AttributeError: 'str' object has no attribute 'quit'
```

**Comment by jhsimpson** [comment]
In a production deployment, the file would be in /usr/lib/archivematica/MCPClient/lib/clientScripts, rather than src/MCPClient/...

**Comment by sevein** [comment]
In #757 I suggest a solution based on the django.core.mail package, instead of using `smtplib` directly. One benefit is that it lets us define a It also brings the benefit of letting us set up different email configuration settings via our settings modules. Currently, MCPClient relies on the framework defaults which results in the same behaviour AM16 has:

- `EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend`
- `EMAIL_HOST=localhost`

That means that AM17 still expects to have locally available a MTA listening on 25/tcp. I believe our packages and Ansible role deploy a Postfix server. In the RDSS fork of Archivematica Richard added support for Amazon SES and Helen added better configuration support via environment variables or the MCPClient INI file, see: https://github.com/JiscRDSS/archivematica/pull/35.

**Comment by sromkey** [comment]
@sevein could you please explain how to QA, then reassign to @currmie. Thanks!

**Comment by sevein** [comment]
The problem was that when email delivery was unsuccessful (e.g. MTA is unavailable) the client script would fail to handle the error gracefully. For this to be tested I guess we would need to reproduce a couple of scenarios:

1. The email settings are set up properly pointing to the SMTP server. In Ansible/packages I think this is typically done with a local Postfix MTA. In this case, emails should be delivered properly to the user.

2. The email settings point to a SMTP server that isn't available. In this case, the email report should return an error (i.e. `Report email was not delivered`) instead of an uncontrolled exception (e.g. `AttributeError: 'str' object has no attribute 'quit') .

Triggering `emailFailReport.py` may not be as easy unless you know off the top of your head a way to cause the workflow to error. What I normally do is to hack one of the client scripts (e.g. `clientScripts/archivematicaMoveTransfer.py` is a good one because it's used early in the transfer) and add a `import sys; sys.exit(1)` - that will cause AM to believe that there was an error and an email will be sent using `emailFailReport.py`.

@sromkey @currmie, as you can see this may require some coordination with @mamedin or @scollazo. Unless you're running AM locally.

**Comment by mamedin** [comment]
Hi, I tested it on a test VM with CentOS 7 and AM 1.7 deployed with ansible.

I changed the `clientScripts/archivematicaMoveTransfer.py`file as Jesús said and I tested it in both suggested scenarios:

1. The email settings are set up properly pointing to the SMTP server: I receive the error email. (looks OK)
2. The email settings point to a SMTP server that isn't available:
   - I added the line "relayhost = 1.2.3.4" to `/etc/postfix/main.cf`
   - I started the transfer and I could see on /var/log/maillog:
```
Apr 23 17:26:19 mamedin-centos-mariadb postfix/smtpd[23107]: connect from localhost[::1]
Apr 23 17:26:19 mamedin-centos-mariadb postfix/smtpd[23107]: 6399A2FFB: client=localhost[::1]
Apr 23 17:26:19 mamedin-centos-mariadb postfix/cleanup[23110]: 6399A2FFB: message-id=<20180423152619.23102.86805@mamedin-centos-mariadb>
Apr 23 17:26:19 mamedin-centos-mariadb postfix/qmgr[23060]: 6399A2FFB: from=<ArchivematicaSystem@archivematica.org>, size=1912, nrcpt=1 (queue active)
Apr 23 17:26:19 mamedin-centos-mariadb postfix/smtpd[23107]: disconnect from localhost[::1]
Apr 23 17:26:49 mamedin-centos-mariadb postfix/smtp[23111]: connect to 1.2.3.4[1.2.3.4]:25: Connection timed out
Apr 23 17:26:49 mamedin-centos-mariadb postfix/smtp[23111]: 6399A2FFB: to=<mamedin@artefactual.com>, relay=none, delay=30, delays=0.01/0.01/30/0, dsn=4.4.1, status=deferred (connect to 1.2.3.4[1.2.3.4]:25: Connection timed out)
```
  - The microservice "Email fail report" finished and the transfer was moved to the failed directory as expected.

So It looks good to me.
