### ISSUE TITLE
Problem:  There is an (unused) duplicate 'watchedDirectories' folder

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#627]
Inside the sharedDirectory structure, there is this folder:

https://github.com/artefactual/archivematica/tree/stable/1.6.x/src/MCPServer/share/sharedDirectoryStructure/watchedDirectories/watchedDirectories/system/autoProcessSIP

As far as I can tell it is unused, and could be removed.  I think it is confusing to have a folder with a path 'watchedDirectories/watchedDirectories' like that. I am not sure if there is a reason for this, but I can't find a place where this is used.

**Comment by sevein** [comment]
Merged!
