### ISSUE TITLE
Problem: AIP download is unnamed

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#646]
In 20661356c8b20dfbf2d5969234ccb6607407b149 we added to Dashboard the ability to stream AIPs to the browser that are served by the Storage Service. We're using [stream_file_from_storage_service](https://github.com/artefactual/archivematica/blob/92d7abd238585e64e6064bc3f1ddfc663c4d3ace/src/dashboard/src/components/helpers.py#L338-L348) which gets the job done but it does not set the filename. In Chrome that results in a file named `download`, in Firefox the file is named  randomly.

In Firefox, the download never finishes.

**Comment by helenst** [comment]
@sevein I've fixed the filename issue in PR #650. I am not sure about the issue of the download not finishing - I am not seeing this happen in my Firefox. Could it be related to the Content-Disposition headers not having been set properly (and if so, does it work now?)

**Comment by sevein** [comment]
> Could it be related to the Content-Disposition headers not having been set properly (and if so, does it work now?)

I'm sure that's the case!

**Comment by sevein** [comment]
Thanks!
