### ISSUE TITLE
Problem: FIDO does not support pronom version 90

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#652]
Archivematica 1.6.0 includes fido v 1.3.5, which by default supports PRONOM version 88.

In March 2017, The National Archives of the UK released PRONOM v 90.

Today a new version of FIDO (v.1.3.6) was released, which supports PRONOM v90.  Archivematica should be updated to use this new version of Fido.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/archivematica/commit/1fef2133f1528f238bd2bef8309f94e233dcd62c and https://github.com/artefactual/archivematica/commit/73fae41e83ac582593887d7547b6fd561c0bf5da.
