### ISSUE TITLE
Problem: AM agent version stored in multiple places

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#658]
When we make releases we need to change:
- The version number constant (e.g. #656 and #657)
- The agent version number (e.g. https://github.com/artefactual/archivematica/issues/793) (uses Agents model) - we should stop doing this!
- Possibly more places.

**Comment by sevein** [comment]
Related: https://packaging.python.org/guides/single-sourcing-package-version/.

**Comment by ross-spencer** [comment]
Moved to https://github.com/archivematica/Issues/issues/383
