### ISSUE TITLE
Problem: unable to run migrations in default install

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#661]
When running the migrations step on a clean install, it fails due to not being able to load the autoslug module.

I think this is caused by 7d0cef6735 , but I'm not sure if this is a bug in am, or in the am deployment playbooks. @sevein , what do you think?

Full error:
`
TASK [external-roles/artefactual.archivematica-src : Run migrations (within dashboard virtualenv)] ***
fatal: [santi]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput --settings=settings.common --pythonpath=/usr/lib/archivematica/archivematicaCommon", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line\n    utility.execute()\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 328, in execute\n    django.setup()\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate\n    app_config.import_models(all_models)\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/apps/config.py\", line 198, in import_models\n    self.models_module = import_module(models_module_name)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/opt/archivematica/archivematica/src/dashboard/src/fpr/models.py\", line 13, in <module>\n    from autoslug import AutoSlugField\nImportError: No module named autoslug\n", "path": "/usr/share/python/archivematica-dashboard/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", "state": "absent", "syspath": ["/tmp/ansible_KbYHSp", "/tmp/ansible_KbYHSp/ansible_modlib.zip", "/tmp/ansible_KbYHSp/ansible_modlib.zip", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages", "/usr/lib/pymodules/python2.7"]}
`

**Comment by sevein** [comment]
Oh! I see what's going on, django-autoslug is only used by fpr-admin. In qa/1.x, django-autoslug is automatically installed when we install fpr-admin as a package. In stable/1.6.x, fpr-admin is still installed as a submodule. I think that I should keep django-autoslug out of requirements.txt in qa/1.x but to readd it to stable/1.6.x.
