### ISSUE TITLE
Configuration cleanup (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica#664]
Integrate work from https://github.com/JiscRDSS/archivematica/pull/3 into core Archivematica

This makes improvements to the configuration such that config is no longer shared between components, and it can be configured either in a config file or through environment variables.

This was added to the fork after the Docker work (https://github.com/artefactual/archivematica/issues/663), but might be possible without merging that first.

It will also require consideration of https://github.com/JiscRDSS/archivematica/issues/9 - the work in the Jisc PR changes the way the whitelist is used in authentication.

**Comment by helenst** [comment]
I've started doing this on a branch:

https://github.com/helenst/archivematica/compare/dev/clean-up-config...helenst:dev/auto-deployment

It works and does the install stuff - I wanted to try and address https://github.com/JiscRDSS/archivematica/issues/9 here since the original Jisc PR is the one that changes this behaviour. So far I've set it up as per my suggestion there. I'm not sure if we still want the migration that added - perhaps the default whitelist can go back to being 127.0.0.1?

Also a question of whether the ansible scripts should be changed to (optionally) use this rather than just setting up the test user, similar to how it is done with Docker.

**Comment by sevein** [comment]
> It works and does the install stuff - I wanted to try and address JiscRDSS#9 here since the original Jisc PR is the one that changes this behaviour. So far I've set it up as per my suggestion there. I'm not sure if we still want the migration that added - perhaps the default whitelist can go back to being 127.0.0.1?

That's reasonable. I didn't realize until know that I introduced a migration in the RDSS fork, perhaps I shouldn't have done that. I'm worried that the divergence will make harder to maintain the two, what do you think? I don't want that to influence our decision about the whitelist but at the same time I think that trusting localhost makes very little sense. What if the attacker manages to proxy the request from another service running on the same machine?

> Also a question of whether the ansible scripts should be changed to (optionally) use this rather than just setting up the test user, similar to how it is done with Docker.

I think so, that'd be a really nice improvement.

**Comment by helenst** [comment]
oops, just realised I meant to make that comment on #665 - continuing discussion there...

**Comment by sevein** [comment]
#670 was merged!
