### ISSUE TITLE
Automatic deployment of Archivematica (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica#665]
Merge work from https://github.com/JiscRDSS/archivematica/pull/4 into core Archivematica

This allows automated deployment of Archivematica.

https://github.com/JiscRDSS/archivematica/pull/12 might also be part of this.

It would be helpful if https://github.com/artefactual/archivematica/issues/664 was merged in first as this work makes use of some environment config.

Related issue for SS: https://github.com/artefactual/archivematica-storage-service/issues/209

**Comment by helenst** [comment]
... continuing discussion I accidentally started on #664...

> That's reasonable. I didn't remember that I introduced a migration in the RDSS fork, perhaps I shouldn't have done that. I'm worried that the divergence will make harder to maintain the two databases, what do you think?

That's a really good point, I agree that having different migrations across the forks is something that should be avoided! Perhaps we could have an empty whitelist by default, and add an extra param in the install script to set one up?

> I don't want that to influence our decision about the whitelist but at the same time I think that trusting localhost makes very little sense. What if the attacker manages to proxy the request from another service running on the same machine?

The way I've written it here, the empty whitelist is _more_ permissive than `127.0.0.1`, since empty whitelist means no whitelist. Maybe that's not as intuitive as I thought it was? The alternative might be to keep the whitelist the way it was, and have an explicit flag to "use whitelist".

You're right that we definitely can't fully trust IP-based auth, which is why it's good we have it as an 'and' rather than an 'or' with the API key.

**Comment by sevein** [comment]
a36a9bf21636a978b0069e750587e627c0f6742a
