### ISSUE TITLE
Shibboleth integration (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica#666]
Merge work from https://github.com/JiscRDSS/archivematica/pull/5 and https://github.com/JiscRDSS/archivematica/pull/20 into Archivematica core.

This enables Shibboleth authentication (optionally) to allow login from academic institutions. The Archivematica functionality should not concern itself with implementation of Shibboleth protocols - it will simply respond to authentication headers received from the web server and use those to create and configure users.

It would be helpful to first merge https://github.com/artefactual/archivematica/issues/665 which provides some refactors around the welcome screen that are used here.

Related SS issue: https://github.com/artefactual/archivematica-storage-service/issues/210

**Comment by helenst** [comment]
Branch here: https://github.com/helenst/archivematica/compare/dev/auto-deployment...helenst:dev/shibboleth (This will become a PR once #681 is merged)

**Comment by sevein** [comment]
#681 is merged now, @helenst :)

**Comment by sallain** [comment]
Added as part of https://github.com/artefactual/archivematica-docs/pull/46
