### ISSUE TITLE
Add automated workflow option (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica#667]
Merge work from https://github.com/JiscRDSS/archivematica/pull/15 into core.

This adds an automated workflow configuration to Archivematica. Uses config so possibly best done after https://github.com/artefactual/archivematica/issues/664

**Comment by helenst** [comment]
Builds on work done in #681 (when the processing config was brought into code rather than from a file)

Branch here: https://github.com/helenst/archivematica/compare/dev/auto-deployment...helenst:dev/automated-workflow

**Comment by sevein** [comment]
#681 is now merged!
