### ISSUE TITLE
Add default location option (merge from Jisc fork)

### ISSUE THREAD

**Issue by helenst** [artefactual/archivematica#669]
Merge work from https://github.com/JiscRDSS/archivematica/pull/22 into core.

This adds a default location option to the storage directories.

Related SS issue: https://github.com/artefactual/archivematica-storage-service/issues/211

**Comment by helenst** [comment]
I'm doing this on the same branch as #667 since it relies heavily on the work there - will PR them together.

Branch here: https://github.com/helenst/archivematica/compare/dev/auto-deployment...helenst:dev/automated-workflow

**Comment by sallain** [comment]
See comment re: testing on the related Storage Service issue: https://github.com/artefactual/archivematica-storage-service/issues/211

**Comment by sallain** [comment]
This has been documented in archivematica-docs/user-manual/administer.rst (_Processing configuration fields_) as well as in the Storage Service documentation.
