### ISSUE TITLE
Workflow fixes related to DIP Upload & Store

### ISSUE THREAD

**Issue by nickwilkinson** [artefactual/archivematica#691]
From to PR #680:

> Changes to the workflow and related client scripts so that the "Upload DIP" and "Store DIP" decision points make more sense and allow for preconfigured choices for "Store DIP" AFTER "Upload DIP". See RM issue [11195](https://projects.artefactual.com/issues/11195) and closed PR #672.

**Comment by sevein** [comment]
#680 is merged.

**Comment by sallain** [comment]
Waiting on https://github.com/artefactual/archivematica/issues/729 before this can be QA'd
