### ISSUE TITLE
Change head branch in repository from stable/1.6.x to qa/1.x (or master)

### ISSUE THREAD

**Issue by minusdavid** [artefactual/archivematica#700]
I've noticed that Github defaults to the stable/1.6.x branch and it's because the head branch for the repository is stable/1.6.x. 

I think most projects I've worked on tend to have master as the HEAD branch. While archivematica doesn't have a master branch, perhaps it should be changed to qa/1.x? 

I know when I cloned the repository to write a patch, I accidentally worked off stable/1.6.x rather than qa/1.x (or master) because it was the branch that was created during cloning.

**Comment by sevein** [comment]
Thanks for the suggestion, @minusdavid. That was a deliberate choice that we prefer to maintain. I think to some extent this has to do with the idea of providing defaults that target production environments.

We're hoping to solve #704 soon so qa/1.x won't include symlinks. You could clone with `git clone -b qa/1.x repo_url` to have git checking out the desired branch automatically for you.

**Comment by minusdavid** [comment]
Fair enough!

I wasn't aware of that syntax. That's cool. It doesn't really help in an Ansible context I think, but I'll keep note of that for other times!
