### ISSUE TITLE
Problem: editing notes in appraisal tab can delete data from ArchivesSpace

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#713]
more details here: https://projects.artefactual.com/issues/10864

Editing of notes should be disabled in the appraisal tab as a workaround.

**Comment by jraddaoui** [comment]
PR for stable/1.6.x: https://github.com/artefactual/archivematica/pull/714

I'll create one for qa/1.7.x once https://github.com/artefactual/archivematica/pull/678 gets merged

**Comment by jraddaoui** [comment]
https://github.com/artefactual/archivematica/pull/714 was reviewed in the appraisal-tab repository and has been merged.

https://github.com/artefactual/archivematica/pull/678 is still in progress

**Comment by jraddaoui** [comment]
https://github.com/artefactual/archivematica/pull/678 has been merged

**Comment by kellyannewithane** [comment]
firewall issues too - does this need to be documented better?

**Comment by kellyannewithane** [comment]
On AM17xqa

Transfer 'archivesspacetest' 

Failed at Job: Upload to ArchivesSpace. 

STDERR:
usage: upload-archivesspace.py [-h] [--host host] [--port port] [--user USER]
                               [--passwd PASSWD] [--dip_location DIP_LOCATION]
                               [--dip_name DIP_NAME] [--dip_uuid DIP_UUID]
                               [--restrictions {yes,no,premis}]
                               [--object_type OBJECT_TYPE]
                               [--xlink_actuate {none,onLoad,other,onRequest}]
                               [--xlink_show {embed,new,none,other,replace}]
                               [--use_statement USE_STATEMENT]
                               [--uri_prefix URI_PREFIX]
                               [--access_conditions ACCESS_CONDITIONS]
                               [--use_conditions USE_CONDITIONS]
                               [--inherit_notes INHERIT_NOTES] [--version]
upload-archivesspace.py: error: argument --restrictions: invalid choice: '%restrictions%' (choose from 'yes', 'no', 'premis')

**Comment by nickwilkinson** [comment]
Hi @jraddaoui , can you please take a look at the problems Kelly documented above?

**Comment by jraddaoui** [comment]
I have moved this to https://github.com/artefactual/archivematica/issues/746, since it's not fully related with this problem.
