### ISSUE TITLE
leave language option in 1.7?

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#723]
Archivematica dashboard only partially translated to French - should we remove language from Administration tab until 1.8?

**Comment by sevein** [comment]
I think that's reasonable, but this is also a good opportunity to start testing this feature before its completion. I'm thinking of it as a [feature toggle](https://en.wikipedia.org/wiki/Feature_toggle)). We could only disable the [LocaleMiddleware](https://docs.djangoproject.com/en/1.8/ref/middleware/#django.middleware.locale.LocaleMiddleware) which is the code responsible for picking the most suitable language for the user based in [the browser preferences](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language). That would leave the choice up to the user in 1.7 (via admin tab), and we could enable automatic content negotiation in 1.8. Thoughts?

**Comment by sevein** [comment]
FYI: automatic language selection is ultimately restricted by our predefined list of supported languages which is [here](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/settings/base.py#L120-L124):

```python
# https://docs.djangoproject.com/en/dev/ref/settings/#languages
LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
    ('es', _('Spanish')),
]
```

E.g.: as it is now a user which runs a browser only advertising Italian as an accepted language will result in our locale middleware picking English.

**Comment by sevein** [comment]
Reminder: the suggested change would need to happen in both Dashboard and Storage Service I'm assuming.

**Comment by jhsimpson** [comment]
I like the idea of disabling the LocaleMiddleware - default to English, but allow a user to set French or Spanish via a setting in the admin tab.  Doing this in the dashboard at a minimum, I think we could just disable French and Spanish as choices in the storage service, unless that is super easy to implement as a toggle.
