### ISSUE TITLE
Problem: FITS/JHOVE is out of date

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#724]
@axfelix reported that FITS/JHOVE was experiencing some issues in 1.6.1. Would be nice to upgrade to the latest version of JHOVE for 1.7.

**Comment by scollazo** [comment]
We build jhove-1.16.7 for centos, but use jhove-1.6 from official ubuntu repositories.

I'll try to build an updated jhove ubuntu package

**Comment by scollazo** [comment]
Built jhove-1.16.7 for ubuntu ( artefactual-labs/am-packbuild@306e078bdfb7e85f40e035249279ee4f6e22b41a) . The package has been signed and is available at https://packages.archivematica.org/1.7.x-alpha/ubuntu-externals/ repository

**Comment by sevein** [comment]
@scollazo does that mean that this issue can be closed now?

**Comment by sevein** [comment]
@scollazo what do you think?

**Comment by sromkey** [comment]
@scollazo Can we resolve this for the release?

**Comment by scollazo** [comment]
Packages jhove_1.16.7-1+14.04 and jhove_1.16.7-1+16.04 has been added to the 1.7.x/ubuntu-extras repo

The packages have been built by hand, and uploaded to the repo based on this pr: https://github.com/artefactual-labs/am-packbuild/pull/104

**Comment by axfelix** [comment]
Thanks folks, glad to see this :)

**Comment by sallain** [comment]
Thanks @scollazo! Closing this; it can be reopened if needed.
