### ISSUE TITLE
Problem: ghostscript is out of date

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#725]
A user reported on the forum that the current version of ghostscript (9.07) contains a [limitation related to filepath length](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/archivematica-tech/cifymsOab2U/jfIuh_8xBgAJ). Upgrading to a more recent version solved this issue.

Documentation is also difficult to find for ghostscript 9.07 so upgrading commands is difficult.

**Comment by scollazo** [comment]
For the record, this only affects rhel/centos, that have gs 9.07. For ubuntu environments, Canonical provides  gs version 9.10~dfsg-0ubuntu10 for trusty, and 9.18~dfsg~0-0ubuntu2 for xenial.

**Comment by scollazo** [comment]
There is a new ghostscript 9.20 package for centos/rhel ( artefactual-labs/am-packbuild@954e49b459fa663cd6423ed584bf62cae1780ec6) available at https://packages.archivematica.org/1.7.x-alpha/centos-extras/

**Comment by sromkey** [comment]
@scollazo Is any action needed to prepare this for the release?
