### ISSUE TITLE
FITS (nailgun) not working correctly on Xenial Ansible installs

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#726]
To recreate: 

1. deploy AM to a Xenial VM using https://github.com/artefactual/deploy-pub/tree/master/playbooks/archivematica-xenial
2. Create a transfer and view the "Characterize and extract metadata" micro-service
3. View the task details and see `Command FITS failed with exit status 127; stderr: /tmp/<UUID>: line 5: ng: command not found`

**Comment by sevein** [comment]
I think that #732 was closed accidentally. @scollazo is working on it.

**Comment by sromkey** [comment]
@scollazo or @mamedin can you confirm if this can be tested on either of our testing VMs (e.g. are they on Xenial).
