### ISSUE TITLE
pip install times out when downloading dependencies

### ISSUE THREAD

**Issue by lwo** [artefactual/archivematica#728]
When installing dependencies on an Ubuntu 14.04 lts with pip, the request times out when a dependency protocol is prefixed with git+git

Replacing it with a -https prefix solved this issue for us and the install thus continues.
Is there a better way to deal with this? Or could you merge this in?

repo: artefactual/archivematica
branch: qa/1.x
file: src/dashboard/src/requirements/base.txt

```
-git+git://github.com/Brown-University-Library/django-shibboleth-remoteuser.git@67d270c65c201606fb86d548493d4b3fd8cc7a76#egg=django-shibboleth-remoteuser
+git+https://github.com/Brown-University-Library/django-shibboleth-remoteuser.git@67d270c65c201606fb86d548493d4b3fd8cc7a76#egg=django-shibboleth-remoteuser

-git+git://github.com/seatme/django-longer-username.git@seatme#egg=longerusername
+git+https://github.com/seatme/django-longer-username.git@seatme#egg=longerusername
```

repo: artefactual/archivematica
branch: qa/1.x
file: src/MCPClient/requirements/base.txt
```
-git+git://github.com/artefactual-labs/ammcpc@v0.1.1#egg=ammcpc
+git+https://github.com/artefactual-labs/ammcpc@v0.1.1#egg=ammcpc
```

repo: artefactual/archivematica-storage-service
branch: qa/0.x
file: requirements/base.txt

```
-git+git://github.com/Brown-University-Library/django-shibboleth-remoteuser.git@67d270c65c201606fb86d548493d4b3fd8cc7a76
+git+https://github.com/Brown-University-Library/django-shibboleth-remoteuser.git@67d270c65c201606fb86d548493d4b3fd8cc7a76

-git+git://github.com/seatme/django-longer-username.git@seatme#egg=longerusername
+git+https://github.com/seatme/django-longer-username.git@seatme#egg=longerusername
```

**Comment by sevein** [comment]
@lwo, thanks for the report! We've made this same mistake before (86166b5a19bff01aada09a22181be1d475b52a49). I will file a PR soon. Thank you!

**Comment by sevein** [comment]
[@repson](https://github.com/repson) was looking for ways to contribute to the project. I've suggested him to address this one, it can be a good start.

**Comment by repson** [comment]
@sevein I just created two pull requests solving the problem. Thanks!
