### ISSUE TITLE
Store DIP fails 

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#729]
On a new AM 1.x VM, the following condition fails at Store DIP:

- DIP upload: Do not upload
- Store DIP: Store in standard Archivematica directory

The error output reads:
`OSError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/uploadedDIPs/tester-img-b161664e-dfd3-45a0-87bd-9cc36c14643e'`

May be related to #680.

**Comment by jrwdunham** [comment]
This should be fixed by [PR 741](https://github.com/artefactual/archivematica/pull/741) which needs CR.

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual/archivematica/pull/741.
