### ISSUE TITLE
Problem: transfer compliance verification fails in full re-ingest

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#734]
I created a transfer off `SampleTransfers/Images/pictures` (2 objects). Once I had an AIP in the archival storage I re-ingested it (full transfer). I started the new transfer from the Transfer tab but two jobs are failing:

- Job: Verify transfer compliance Failed
- Job: Attempt restructure for compliance

I'm not sure if this is a bug or a feature, it doesn't look good to me.
CC @sallain @kellyannewithane

**Comment by sevein** [comment]
It can't be reproduced again.

**Comment by jlj5aj** [comment]
We are encountering this issue on a full re-ingest of an AIP from archival storage (Archivematica 1.7.2).  I believe we can reliably reproduce it.  Please let me know what information would help for debugging, and also whether I should create a new issue for this.

**Comment by sallain** [comment]
Hi there,

There are few issues currently filed in the Archivematica Issues repo
<https://github.com/archivematica/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+reingest>
for
reingest-related problems. Note that issues with the label *Status:
verified* have been fixed for the upcoming release 1.8.

If you want to report a newly-discovered issue, you can do that here or in
the Issues repo - both are appreciated! In general, the most helpful bug
reports include:

   -  A description of the issue
   - Steps to recreate the issue
   - Information about your environment (version, deployment method, OS,
   etc.)

Any log outputs that you're able to capture are often helpful, as well.


Sara Allain, MI
Systems Archivist
Artefactual Systems, Inc. <https://www.artefactual.com/>

I recognize and acknowledge that the land on which I work is the
traditional and unceded territory of the QayQayt First Nation.
