### ISSUE TITLE
Problem: fiwalk characterization is broken

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#755]
We have a class in [src/archivematicaCommon/lib/externals/fiwalk_plugins/pronom_ident.py](https://github.com/artefactual/archivematica/blob/qa/1.x/src/archivematicaCommon/lib/externals/fiwalk_plugins/pronom_ident.py#L33) that subclasses `fido.Fido` (from https://github.com/openpreserve/fido).

```python
class FiwalkFido(fido.Fido):
    """docstring for FiwalkFido"""
    # [...]
    def identify_file(self, filename):
        """Identify the type of @param filename."""
        # [...]
        bofbuffer, eofbuffer = self.get_buffers(f, size, seekable=True)
```

The method `get_buffers` is treated as it returned a tuple of two items however the method changed a long time ago starting to return a tuple of three items: https://github.com/openpreserve/fido/blob/master/fido/fido.py#L536-L582.

It seems that this change was introduced in v1.3.4-84: https://github.com/openpreserve/fido/commit/d3d5e2368cdc633fd8125d2c1b3f234d9ccbda54.

---

Redmine: https://projects.artefactual.com/issues/11256 (private)

**Comment by sromkey** [comment]
This should be testable by testing the ISO disk image in sample transfers.
