### ISSUE TITLE
Problem: AIP reingest metadata only fails at Job: Populate database with reingested AIP data

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#759]
on am17x.qa

Module parseMETStoDB_v1.0
9b42c237-2728-452f-99e0-19280a7e03ab /var/archivematica/sharedDirectory/currentlyProcessing/onemoretry-9b42c237-2728-452f-99e0-19280a7e03ab/
Standard streams

Standard output (stdout)
METS Reader
filegrpuse deleted
amdid amdSec_1
file_uuid 35611f36-29c7-48bb-98c0-04448fbcaaf6
original_path %SIPDirectory%objects/Landing_zone-35611f36-29c7-48bb-98c0-04448fbcaaf6.tif
Standard error (stderr)
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/parse_mets_to_db.py", line 459, in <module>
    sys.exit(main(args.sip_uuid, args.sip_path))
  File "/usr/lib/archivematica/MCPClient/clientScripts/parse_mets_to_db.py", line 444, in main
    files = parse_files(root)
  File "/usr/lib/archivematica/MCPClient/clientScripts/parse_mets_to_db.py", line 69, in parse_files
    current_path = fe.find('mets:FLocat', namespaces=ns.NSMAP).get(ns.xlinkBNS + 'href')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by sevein** [comment]
@kellyannewithane can you include steps to reproduce the issue? I haven't been able to reproduce.

**Comment by kellyannewithane** [comment]
@sevein I believe this has been fixed but I couldn't find the pull request. I couldn't reproduce the issue either.  I think @jrwdunham worked on it.
