### ISSUE TITLE
Problem: Icons missing from ArchivesSpace tab on Appraisal pane

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#760]
Should have (according to the 1.6.1 docs)

-Folder icons to indicate ArchivesSpace resources and archival objects which have child records nested under them. 
-Page icons to indicate resources and archival objects that do not have child records. 
-Parallel lines icons for digital object components

**Comment by ross-spencer** [comment]
Hi @kellyannewithane what is the best way for me to begin to recreate this issue?

**Comment by ross-spencer** [comment]
The documentation shows the following: 

![image](https://user-images.githubusercontent.com/1880412/34175659-da486730-e4c2-11e7-85f9-e660b45634cf.png)

vs. qa17x server:

![image](https://user-images.githubusercontent.com/1880412/34180890-e0ccfbee-e4d5-11e7-8b89-5fce59cd5ffe.png)

**Issue:**

The tree is driven by this AngluarJS Control:

- Source: https://github.com/wix/angular-tree-control
- Demo: http://jsfiddle.net/8ApLX/5/

And we have configured tree-light for ArchivesSpace:

https://github.com/artefactual/archivematica/blob/d0441aff02e5e5da24d2351881edc4f4eaf455d8/src/dashboard/frontend/appraisal-tab/app/front_page/content.html#L244

Other parts of the Appraisal window are configured to use tree-classic:

https://github.com/artefactual/archivematica/blob/d0441aff02e5e5da24d2351881edc4f4eaf455d8/src/dashboard/frontend/appraisal-tab/app/front_page/content.html#L318

Switching these various options in and out and rebuilding the `bootstrap-dashboard-frontend` components fixes the issue. We just need to confirm that we don't see any unanticipated side effects. It will be useful to understand the regression if possible as well.

**Comment by ross-spencer** [comment]
This fix should also ensure that the other icons are consistent with what we're expecting too as described in #859. Described as:

> When a new resource shows up on the ArchivesSpace pane of the Appraisal tab, the icon is a document. When a digital object is added to that resource the icon changes from a document to a folder.

**Comment by ross-spencer** [comment]
Some screenshots from **1.6.1**.

![image](https://user-images.githubusercontent.com/1880412/34268487-80cc4ad4-e646-11e7-8d1c-d84a7dfff0b7.png)
![image](https://user-images.githubusercontent.com/1880412/34268445-50b97204-e646-11e7-94e8-ff8d573f8455.png)
![image](https://user-images.githubusercontent.com/1880412/34268502-8f178de2-e646-11e7-82cf-5c6b5c49a26b.png)
![image](https://user-images.githubusercontent.com/1880412/34268464-662a2fde-e646-11e7-9a31-e2a8cbb1eef9.png)

**Comment by ross-spencer** [comment]
Some screenshots from **1.7.x**:

![image](https://user-images.githubusercontent.com/1880412/34269570-712737d4-e64a-11e7-8a5a-6a62bbc1cfd5.png)
![image](https://user-images.githubusercontent.com/1880412/34269552-5f42ad46-e64a-11e7-972a-4c99e665c932.png)
![image](https://user-images.githubusercontent.com/1880412/34269537-4ee42c68-e64a-11e7-8606-1cc36b82cfd6.png)

![image](https://user-images.githubusercontent.com/1880412/34269520-3f7f1850-e64a-11e7-8229-66c2527ab30a.png)

**Comment by ross-spencer** [comment]
@kellyannewithane @sromkey I've got about as far as I can with this before the holidays. Regarding #760 (noted above) It seems that there is a precedent for the icon to be selected appropriately, but it is not 100% clear whether it was a feature previously. I don't think so. (See the icons for [1.6.1 Sub-series 3.1](https://github.com/artefactual/archivematica/issues/760#issuecomment-353417053) is a document icon before becoming a folder). We set the `digital object` icon correctly I think through this line of code https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/dashboard/frontend/appraisal-tab/app/archivesspace/archivesspace.controller.js#L285 but this is me finding this quite late in the day after trying to learn the external component we're using so that might not be 100% accurate. 

I think if we take 6.1.1 as a baseline then we should close this issue and and add the icons issue as a feature for the future release. I can write that up if you agree. Let me know below. 

For changing the icons to be consistent with the others on the Appraisal Tab, then that is covered by this PR, https://github.com/artefactual/archivematica/pull/858 which I can merge first thing next week.

**Comment by kellyannewithane** [comment]
@ross-spencer @sromkey I agree, we can close this issue and add the icons issue for the next (or future) release.

**Comment by sromkey** [comment]
Sounds like a good plan to me too.

**Comment by ross-spencer** [comment]
Best Christmas present yet! :smiley:

**Comment by ross-spencer** [comment]
@kellyannewithane @sromkey I was reading the docs and noticed that the fix still doesn't quite match what we had previously. Below I suggest that we revert back to the style in 1.6.1, and consider alternatives for a future version of Archivematica. Let me know what you think.

I have tracked down the original issue now and can propose a different fix with the following result:

![image](https://user-images.githubusercontent.com/1880412/34413824-5471a938-ebab-11e7-96f3-83aab5179a34.png)

Notice the style now matches:

![image](https://user-images.githubusercontent.com/1880412/34413856-a0563ff8-ebab-11e7-927d-73c443731e61.png)

Via. https://www.archivematica.org/en/docs/archivematica-1.6/user-manual/appraisal/appraisal/#archivesspace-pane

**Fix**

List font-awesome into the appraisal-tab:

```
+++ b/src/dashboard/frontend/appraisal-tab/package.json
+    "font-awesome": "^4.3.0",
```

Import font-awesome into the appraisal-tab:

```
+++ b/src/dashboard/frontend/appraisal-tab/app/app.js
+import 'font-awesome/css/font-awesome.min.css';
```

And reset the tree-control to the 'light' version:

```
+++ b/src/dashboard/frontend/appraisal-tab/app/front_page/content.html
     </div>
     <div class="transfer-tree panel-body">
       <treecontrol id="archivesspace-tree"
-             class="tree-classic"
```

This will revert a regression that occurred between 1.6.1 and 1.6.x in the following two commits:

https://github.com/artefactual-labs/appraisal-tab/commit/9c4a070cfc43835b5fcf9943e0f9218f19a70a3a
https://github.com/artefactual-labs/appraisal-tab/commit/0446eda8f36d73655109a2e6b6f557613082a451

To implement this now will only take a short amount of time.

**Comment by jraddaoui** [comment]
That looks great @ross-spencer!

I agree we should add it to stable/1.6.x, stable/1.7.x and qa/1.x

**Comment by ross-spencer** [comment]
@jraddaoui will chat to Kelly asap and then once we've decided an approach we'll make the changes to 1.6.x as well.
