### ISSUE TITLE
Dashboard and MCPClient depend on deleted mets-reader-writer branch

### ISSUE THREAD

**Issue by mamedin** [artefactual/archivematica#771]
Hi, I'm deploying AM qa/1.x in augustus for the daily tests.

The `dev/issue-10908-empty-directories` branch of `mets-reader-writer` has been deleted, and it still appears in the python requirements for the dashboard and the MCPClient:

```
root@augustus:/opt/archivematica/archivematica/src# grep -R issue-10908-empty-directories *
dashboard/src/requirements/base.txt:git+https://github.com/artefactual-labs/mets-reader-writer.git@dev/issue-10908-empty-directories
MCPClient/requirements/base.txt:git+https://github.com/artefactual-labs/mets-reader-writer.git@dev/issue-10908-empty-directories
```

**Comment by sevein** [comment]
@jraddaoui is working on this.

**Comment by sevein** [comment]
@jrwdunham is working on this.

**Comment by jrwdunham** [comment]
Should be fixed by https://github.com/artefactual/archivematica/pull/770

**Comment by sevein** [comment]
Thanks for the report, @mamedin.
