### ISSUE TITLE
Problem: StoreDIP is stuck until refresh screen

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#774]
When the DIP is stored after the AIP AM dashboard gets stuck at StoreDIP location.  Refreshing the screen the job reports that the DIP is stored successfully. 

Can this be resolved or should we document a workaround for 1.7?

**Comment by kellyannewithane** [comment]
https://projects.artefactual.com/issues/11476#change-56586

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual/archivematica/pull/777

**Comment by ablwr** [comment]
In regression-testing for DIP workflow in am17x.qa and centos17x.qa, this has not been a problem. I think this is resolved.
