### ISSUE TITLE
Problem:  can't configure logging location easily in 1.7

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#776]
the 1.7 release redirects logs from the dashboard, mcp client and mcp server to stdout and stderr.  These get captured at the moment by systemd (on systems with that) or upstart (on ubuntu 14.04).  

In order to maintain backwards compatibility with how logs are stored in Archivematica 1.6.1 and earlier, there needs to be a way to direct logs to /var/log/archivematica, and to decide what logging level goes into what file.

**Comment by sevein** [comment]
- AM PR: https://github.com/artefactual/archivematica/pull/782
- SS PR: https://github.com/artefactual/archivematica-storage-service/pull/256
- DEB/RPM issue: https://github.com/artefactual-labs/am-packbuild/issues/63
- Ansible role issue: https://github.com/artefactual-labs/ansible-archivematica-src/issues/147

**Comment by sromkey** [comment]
@scollazo or @mamedin could you please QA this?
