### ISSUE TITLE
sanitizeObjectNames fails on submissions with large number of files.

### ISSUE THREAD

**Issue by dnarc** [artefactual/archivematica#789]
On submissions with large number of files (>30,000 or so), sanitizeObjectNames in the "Sanitize file and directory names in submission documentation" workflow fails with the following error in the dashboard console:

"MCP shut down while processing."

I can find no on-disk logs corresponding to this problem and Archivematica keeps on processing the submission, although this issue seems to lead to the submission later failing at the 'Move submission documentation into object directory' micro-service.

Two, probably separate issues:

1. The crash itself, which I suspect is a resource limit error, probably memory, call stack space, or database connection limits, from two pieces of code:

First, from sanitizeNames.py:

    def sanitizeRecursively(path):
    path = os.path.abspath(path)
    sanitizations = {}

    sanitizedName = sanitizePath(path)
    if sanitizedName != path:
        path_key = unicodeToStr(
            unicodedata.normalize('NFC', path.decode('utf8')))
        sanitizations[path_key] = sanitizedName
    if os.path.isdir(sanitizedName):
        for f in os.listdir(sanitizedName):
            sanitizations.update(sanitizeRecursively(os.path.join(sanitizedName, f)))

Second, from sanitizeObjectNames.py:

    for f in File.objects.filter(**kwargs):
        # Check all files to see if any parent directory had a sanitization event
        current_location = unicodeToStr(
            unicodedata.normalize('NFC', f.currentlocation)).replace(
                groupType, sipPath)
        sanitized_location = unicodeToStr(current_location)
        logger.info('Checking %s', current_location)

        # Check parent directories
        # Since directory keys are a mix of sanitized and unsanitized, this is a little complicated
        # Directories keys are in the form sanitized/sanitized/unsanitized
        # When a match is found (eg 'unsanitized' -> 'sanitized') reset the search
        # This will find 'sanitized/unsanitized2' -> 'sanitized/sanitized2' on the next pass
        # TODO This should be checked for a more efficient solution
        dirpath = sanitized_location
        while objectsDirectory in dirpath:  # Stay within unit
            if dirpath in sanitizations:  # Make replacement
                sanitized_location = sanitized_location.replace(dirpath, sanitizations[dirpath])
                dirpath = sanitized_location  # Reset search
            else:  # Check next level up
                dirpath = os.path.dirname(dirpath)
[...]

which I suspect is taxing the database quite a bit.

2. I actually have no submission documentation in this submission, I don't know why this code path is running at all (probably a separate bug or a mis-understanding on my part).

**Comment by ross-spencer** [comment]
For folks wishing to test this, I have been thinking about this recently so I hacked together a sample set from our `createtransfers.py` script. This consists of the following: `3905 directories, 46861 files`. The files are simple markdown with the text:
```
# Archivematica Deep Transfer Sample Set
```
 
[46800-files.zip](https://github.com/artefactual/archivematica/files/2439480/46800-files.zip)

**Comment by ross-spencer** [comment]
Via @hakamine. A setting to look at is: `innodb_log_file_size`  in `/etc/mysql/my.cnf`. 

* Link 1: https://www.percona.com/blog/2011/11/21/should-mysql-update-the-default-innodb_log_file_size/
* Link 2: https://www.percona.com/blog/2017/10/18/chose-mysql-innodb_log_file_size/ 

In an initial test in my docker-compose environment I couldn't get the setting to take hold, so it is something to come back to for anyone looking at this issue.

**Comment by hakamine** [comment]
Excerpt of the MCP Server debug log for one of the servers in which the problem occurred (transfer stalled on sanitize job) for a transfer with 2000+ files. The line previous to the ERROR line is a 3MB+ long `DEBUG` line (pasted below truncated, added the `<TRUNCATED>` text manually, not part of the original log). 

```
DEBUG     2018-10-02 03:34:15  archivematica.mcp.server:taskStandard:check_request_status:103:  Task d003cc1c-79c8-43c9-a2a0-9d5c58166a23 finished! Result COMPLETE - {'stdOut': 'Sanitized name: %transferDirectory%objects/ <TRUNCATED>  
ERROR     2018-10-02 03:34:16  archivematica.mcp.server:utils:wrapped:16:  Uncaught exception
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPServer/lib/utils.py", line 14, in wrapped
    return fn(*args, **kwargs)
  File "/usr/lib/archivematica/archivematicaCommon/databaseFunctions.py", line 47, in wrapper
    return f(*args, **kwargs)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/taskStandard.py", line 96, in performTask
    self.check_request_status(completed_job_request)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/taskStandard.py", line 105, in check_request_status
    self.linkTaskManager.taskCompletedCallBackFunction(self)
  File "/opt/archivematica/archivematica/src/MCPServer/lib/linkTaskManagerDirectories.py", line 76, in taskCompletedCallBackFunction
    databaseFunctions.logTaskCompletedSQL(task)
  File "/usr/lib/archivematica/archivematicaCommon/databaseFunctions.py", line 264, in logTaskCompletedSQL
    task.save()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1118, 'The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.')
```
The `innodb_log_file_size` setting in the mysql instance was `5MB` (default value)

**Comment by jlj5aj** [comment]
We are experiencing this same issue on a submission with ~8000 files.  The DEBUG entry prior to the database going away unexpectedly is roughly 22.5 MB in size:

`DEBUG     2018-09-21 19:37:21  archivematica.mcp.server:taskStandard:check_request_status:103:  Task 392b2d8a-180f-474d-bf56-88802a1ecb68 finished! Result COMPLETE - {'stdOut': '5.5 MB of log info', 'exitCode': 0, 'stdError': '17 MB of log info, including duplicates of each line in stdout'}`

In the past, large stdOut/stdError fields have given us trouble in the "Characterize and extract metadata" step.  If the combined size of these fields exceeded ~1 MB, the script would crash as above, with a note that the database had "gone away".  We worked around this by increasing `max_allowed_packet` in `/etc/my.conf` from the default of 1M to 16M, and that allowed things to progress.

As for this issue, I have increased the `innodb_log_file_size` value and am awaiting another test to see if that helps.  However, based on our earlier experience above, I suspect this is another instance of too much data for the database to handle in a single query, and may require another increase of `max_allowed_packet`.

**Comment by ross-spencer** [comment]
Via @peterVG's testing of this issue: https://github.com/artefactual/archivematica/issues/1104#issuecomment-429096416 we are seeing the same thing happen when the similar `Sanitize extracted contents file and directory names` method happens in the `Extract Contents` group of microservices. 

For those working on this issue or testing it, then doing so against this folder (created by `createtransfers.py` in the sample data repository, will confirm the veracity of any fix: `/home/archivematica/archivematica-sampledata/TestTransfers/sample-zip-packages/deep-transfer/deep_zip_transfer/` (Extract packages needs to be configured in the processing config).

**Comment by nickwilkinson** [comment]
Related to [ansible-percona issue 24](https://github.com/artefactual-labs/ansible-percona/issues/24) and [ansible-percona PR 23](https://github.com/artefactual-labs/ansible-percona/pull/23).

**Comment by sevein** [comment]
Besides being operationally not a [trivial change](https://github.com/artefactual-labs/ansible-percona/issues/24), it occurs to me that increasing `innodb_log_file_size` is just going to push the limit further but we'll eventually hit the same issue. My understanding is that the job is generating a huge blob written into the database within a single transaction. The blob consists in the following two entries repeated for every file present in the transfer:

    logger.info('Sanitized name: %s -> %s', old_location, new_location)
    job.pyprint('Sanitized name:', old_location, " -> ", new_location)

The job seems to complete successfully regardless the number of files - the trade-off is that the the user wouldn't be able to see these entries in the Dashboard. In particular, the second line is important because it populates the contents of `%SIPLogsDirectory%filenameCleanup.log`.

My feeling is that https://github.com/artefactual-labs/ansible-percona/issues/24 isn't going to be an easy change to make available for everyone. A compromise could be to ask users to [disable output capturing](https://github.com/artefactual-labs/ansible-percona/issues/24) unless they want to take the responsibility of increasing `innodb_log_file_size` manually.

In the long term, we probably want to look into blob concatenation or just figuring out a better place to store the data or reconsider its structure, e.g. should we store individual events instead of a plain text blob?

@dnarc is also right that the script is very demanding on the database, in particular `updateFileLocation` is doing a few queries for every file. This is concerning because it's happening within the context of `transaction.atomic()` - although the problem reported seems unrelated.

**Comment by hakamine** [comment]
A couple of thoughts:
- The default value for `innodb_log_file_size` in MySQL/Percona (5MB) is too low for reliable use in production (this has been pointed out since a while ago, e.g., [here](https://www.percona.com/blog/2011/11/21/should-mysql-update-the-default-innodb_log_file_size/). Unfortunately we have been using this default value for most deployments, and updating the value, while not a super complex procedure, [requires some care.](https://github.com/artefactual-labs/ansible-percona/issues/24)
- However I am too with the opinion that increasing `innodb_log_file_size` is just kind of a "band-aid fix" (ingests with even larger number of files may break the server again and required another increase). The real issue seem to be about MCP tables becoming bloated with data that may not actually be needed. I was wondering if disabling output capturing should be the default for archivematica installations, and enabling it only when really needed (debugging?)

**Comment by sevein** [comment]
Moved to verified. We've been running different tests (e.g. [46800-files.zip](https://github.com/artefactual/archivematica/files/2439480/46800-files.zip) and the job passes successfully with task output capturing disabled.

**Comment by sevein** [comment]
@dnarc FYI I've filed a new issue: https://github.com/archivematica/Issues/issues/315. To sum up, it does not fail anymore with some tweaking (see above) but it's still slow!
