### ISSUE TITLE
Problem: agent version number is outdated

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#793]
The `ARCHIVEMATICA_VERSION` constant was updated in https://github.com/artefactual/archivematica/pull/657. But we need a migration like 0011 or 0028 that updates the Agent, basically:

    Agent.objects \
        .filter(identifiertype=‘preservation system’, name=‘Archivematica’) \
        .update(identifiervalue=‘Archivematica-1.7.0’)

This agent is populated by the Dashboard installer. That's why we need migrations.
Related issue: https://github.com/artefactual/archivematica/issues/658.

**Comment by nickwilkinson** [comment]
Related to #853

**Comment by sevein** [comment]
Solved in #853.

**Comment by sromkey** [comment]
To test this we need to upgrade a 1.6.x server to 1.7 and check that the agent number is correct in the METS file.
