### ISSUE TITLE
Problem: CI does not check if migrations are consistent

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#797]
Sometimes new Pull Reqests add code that requires a django migration to be run.  It would be very helpful to add a travis check for this to all PR's.

This tool might do the job:
https://github.com/rev112/django-migration-checker

**Comment by sevein** [comment]
I did something similar in fpr-admin, here: https://github.com/artefactual/archivematica-fpr-admin/blob/qa/1.x/.travis.yml#L7-L15.

**Comment by sevein** [comment]
We have this working in SS: https://github.com/artefactual/archivematica-storage-service/commit/b19aaa39f64c3087e6298ac9283f54dfbe784db7#diff-1a8bb89e4b6a6d450e4dab3b70074e80.

It could be added to the AM repo too.

**Comment by sevein** [comment]
Also in AM, added in https://github.com/artefactual/archivematica/pull/1639.
