### ISSUE TITLE
Problem: user can't choose processing configuration

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#800]
The Dashboard allows the user to create multiple configurations and they can be chosen during re-ingest but not in new transfers.

**Comment by sromkey** [comment]
Are we considering this issue to be fully addressed by #799? With that PR you can download the MCP file but AFAIK there's not a way in the dashboard for users to choose a processing config.

**Comment by sevein** [comment]
Yes, 799 is not enough.

**Comment by sevein** [comment]
@sromkey when you have a chance can you please take a look at the solution suggested in #1222? It does two things: 1) it makes possible via the new Package API to choose the processing configuration by adding an additional attribute `processing_config`, 2) it makes a small change in the transfer browser widget so developers can choose define a value for `processing_config` - as a temporary solution so we can start testing while we figure out the user interface.
