### ISSUE TITLE
Problem: when DISABLE_SEARCH_INDEXING is True, Backlog, Appraisal and Archival storage break

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#803]
If an Archivematica instance is deployed with `DISABLE_SEARCH_INDEXING` set to `True` in dashboard/src/settings/base.py and MCPClient/lib/settings/common.py, then the Backlog, Appraisal and Archival storage tabs will display errors as described below.

- Backlog: `ConnectionError` from `elasticSearchFunctions.get_client()` in dashboard/src/components/backlog/views.py
- Appraisal: clicking "Search transfer backlog" results in notification reading "Unable to retrieve transfer data from Archivematica."
- Archival storage: `ConnectionError` from `elasticSearchFunctions.get_client()` in dashboard/src/components/archival_storage/views.py

Instead of returning HTTP responses with 500 status codes or exposing non-functional search interfaces, these tabs should display a warning to the user that they are non-functional and why.

**Comment by jrwdunham** [comment]
This should be fixed by https://github.com/artefactual/archivematica/pull/804

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual/archivematica/pull/804

**Comment by sromkey** [comment]
This was qa'd as part of the 1.7 release, closing.
