### ISSUE TITLE
Problem: option to review the DIP has disappeared

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#806]
There is no longer an option to Review the DIP. We used to be able to do this at "Job: Move to the uploadedDIPs directory (review)". 

- see [documentation](https://www.archivematica.org/en/docs/archivematica-1.7/user-manual/access/access/#review-dip)
- see [Redmine ticket](https://projects.artefactual.com/issues/11660)

**Comment by ablwr** [comment]
While doing regression testing on DIPs in general, I've seen this button every time! Testing in am17x.qa and centos17x.qa. I'd say this is very resolved.
