### ISSUE TITLE
Clamav fails to scan empty files

### ISSUE THREAD

**Issue by kerim1** [artefactual/archivematica#808]
During testing with the latest code changes from the qa branch, we ran into a problem with the virus scan. When clamav encounters an empty file, it fails with the error message: "Unexpected file size", with a failing transfer as a result. This is new behavior we haven't encountered before and it occurs both in our acceptance environment and a local vagrant installation, so we assume something was changed in the clamav configuration in the commits from the last couple of weeks.

**Comment by sevein** [comment]
@kerim1 would you be able to share the output of the antivirus task? I'm interested to know which filed caused the issue. The function that checks the file size attempts to obtain it from the database file record but if unavailable it will manually run `os.path.getsize`. It looks like in the situation that you're describing the latter failed which is something I wouldn't expect unless maybe the file wasn't readable or something similar.

In any case, @ross-spencer is working on some changes in the antivirus client script. That idea of checking the size of the file to decide whether to scan it with clamd or clamscan was something I suggested but turned out not to be a good idea because both seem to share the same problems with large files - so that logic will likely be removed from the code before 1.7 is released.

Thank you for your feedback!

**Comment by ross-spencer** [comment]
@kerim1 @sevein will make sure to add some zero-size files to the tests. What is expected behaviour for AM with zero-size files - before AV even? They're kind of .DS_Store-esque - little or no value but potential context in an archival environment.

**Comment by kerim1** [comment]
One instance was a zipped bag transfer. The bag contained an empty FileSystemData.txt created by the tool Exactly:

**Module archivematicaClamscan_v0.0**
`"7a2f2e22-d7e7-4fd5-9cda-4fab5c9d2756" "/var/archivematica/sharedDirectory/currentlyProcessing/00 - General collection-8d12eb5e-8011-4a92-ae48-20ac1b642997/logs/BagIt/FileSystemData.txt" "%date%" "%taskUUID%"`

**Standard error (stderr)**
```
archivematicaClamscan.py: ERROR     2017-11-27 09:26:02,001  archivematica.mcp.client.clamscan:scan_file:263:  Unexpected file size
archivematicaClamscan.py: INFO      2017-11-27 09:26:02,001  archivematica.mcp.client.clamscan:record_event:198:  Recording new event for file 7a2f2e22-d7e7-4fd5-9cda-4fab5c9d2756 (outcome: Fail)
```

Another example is the file _empty-file.txt_ from our test collection (see https://github.com/IISH/archivematica-test-collections/tree/master/12%20-%20Damaged%20files ):

**Module archivematicaClamscan_v0.0**
`"43d78360-93eb-4c36-bed7-72a8b9c02bca" "/var/archivematica/sharedDirectory/currentlyProcessing/12 - Damaged files-ce2edcfe-2091-4e61-9447-69c8b882b440/objects/12 - Damaged files/empty-file.txt" "%date%" "%taskUUID%"`

**Standard error (stderr)**
```
archivematicaClamscan.py: ERROR     2017-11-27 09:35:44,700  archivematica.mcp.client.clamscan:scan_file:263:  Unexpected file size
archivematicaClamscan.py: INFO      2017-11-27 09:35:44,700  archivematica.mcp.client.clamscan:record_event:198:  Recording new event for file 43d78360-93eb-4c36-bed7-72a8b9c02bca (outcome: Fail)
```

**Comment by ross-spencer** [comment]
I can verify this with a standard transfer as well:

		archivematicaClamscan.py: ERROR     2017-11-27 16:52:40,041  archivematica.mcp.client.clamscan:scan_file:267:  Unexpected file size
		archivematicaClamscan.py: INFO      2017-11-27 16:52:40,041  archivematica.mcp.client.clamscan:record_event:202:  Recording new event for file 94925a00-fc9

**Comment by ross-spencer** [comment]
We'll just need to nuance this line a bit. 

https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/archivematicaClamscan.py#L262

**Comment by sromkey** [comment]
I think I recreated this using a standard transfer (the images sample directory). I got an error in Scan for viruses in metadata job in Process metadata directory micro-service:

archivematicaClamscan.py: ERROR     2017-11-30 18:04:31,352  archivematica.mcp.client.clamscan:scan_file:263:  Unexpected file size
archivematicaClamscan.py: INFO      2017-11-30 18:04:31,352  archivematica.mcp.client.clamscan:record_event:198:  Recording new event for file c1d8ecef-f2cb-4341-875a-ac76d9af51ee (outcome: Fail)

I did not create any metadata in the UI or include in the transfer- does Archivematica temporarily create an empty metadata.csv? Or is something else happening?

**Comment by ross-spencer** [comment]
@kerim1 @sromkey both issues closely related. We've a fix in place. Have a look at the behaviour now and let us know how it goes.

**Comment by kerim1** [comment]
Is this already merged with the qa branch? According to the linked pull request it is. Yet I don't see the changes in the qa branch?

**Comment by ross-spencer** [comment]
I can't see it either @kerim1 ![image](https://user-images.githubusercontent.com/1880412/33559492-914987f4-d8d2-11e7-8e2e-bb0d0db281cf.png)

qa1.x:

![image](https://user-images.githubusercontent.com/1880412/33559520-ae5888fe-d8d2-11e7-9f09-810ebeb91805.png)

Any ideas @sevein?

**Comment by sevein** [comment]
Sounds like you pushed to the mirror. You should be able to update the remote to point to our git server and `git cherry-pick ed13f3354`.

**Comment by sevein** [comment]
I've just done it: https://github.com/artefactual/archivematica/commit/52801f1f3c43814f0b3c3cff2478d4d81de430b8 now in qa/1.x.

**Comment by currmie** [comment]
Fix verified; current behaviour is as-expected (pass) for virus scan on zero-size files in transfers processed via augustus.qa, am17x.qa, and centos17x.qa. Output of the antivirus task looks like the following across all 3 test environments:

Standard error (stderr)

archivematicaClamscan.py: INFO      2018-02-24 04:39:55,200  archivematica.mcp.client.clamscan:scan_file:339:  Using scanner ClamAV (clamd) (ClamAV 0.99.3 - 24343/Sat Feb 24 01:11:00 2018)
archivematicaClamscan.py: INFO      2018-02-24 04:39:55,200  archivematica.mcp.client.clamscan:pass_by_stream:174:  File contents being streamed to Clamdscan.
archivematicaClamscan.py: INFO      2018-02-24 04:39:55,201  archivematica.mcp.client.clamscan:scan_file:352:  File /var/archivematica/sharedDirectory/currentlyProcessing/currm-virus-test-1-0cb7cf8e-6b77-48a6-bc27-4d608ac84c37/objects/test.zero.byte.no-virus scanned!
archivematicaClamscan.py: INFO      2018-02-24 04:39:55,201  archivematica.mcp.client.clamscan:record_event:235:  Recording new event for file 9750e00d-0698-4d30-ad90-d4c0c302e096 (outcome: Pass)
