### ISSUE TITLE
Failure during METS creation due to recursion limit

### ISSUE THREAD

**Issue by kerim1** [artefactual/archivematica#821]
We were testing the ingest of a collection consisting of 4271 files and 181 folders, which failed during the creation of the METS, near the end of the ingest phase due to the recursion limit being reached. The function in question, `add_normative_structmap_div / archivematicaCreateMETS2.py`, seems to recursively loop over all the files and folders in order to create the normative structural map. And as by default the recursion limit is set to 1000 in Python, it suggests that every SIP consisting over 1000 files/folders will fail due to this limit. As it seems quite trivial, I replaced the recursive call with a simple for loop. See commit https://github.com/IISH/archivematica/commit/f5ad80db6b1cbc64330c854266915d7f7aa17ff9 This time it succeeded in creating the METS file with a seemingly ok normative structural map. But as I am not sure whether this is the correct solution, I decided not to open a pull request, but create this ticket instead.

**Comment by jhsimpson** [comment]
I think it would be useful for you to open a pull request @kerim1 .

**Comment by sromkey** [comment]
@currmie either @jrwdunham or @ross-spencer may have some advice about how to generate a transfer large enough to test this.

**Comment by ross-spencer** [comment]
@jrwdunham I can create something like this later unless you've a sample ready? - @currmie I'd suggest the samples folder otherwise, but there are files in there that would make the transfer fail and we probably want to make sure it goes through pretty smoothly for this error to occur.

**Comment by jrwdunham** [comment]
@ross I don't have anything. Maybe you could create a new command in the createTransfers script of sampledata that creates a transfer with very many very small files. This could be processed by AM quickly but still allow us to experiment with how AM deals with very large METS files.

**Comment by ross-spencer** [comment]
Sounds good. Will have something for tomorrow.

**Comment by ross-spencer** [comment]
Commits relevant to this issue:

* Immediately prior to this fix: `8593b7d5f96c23f037a085005adc8c7c96a2e200`
* The fix itself: `71892b4c20a3f25617b6c43f819141793d01a26f`

**Comment by ross-spencer** [comment]
@currmie cc. @sromkey:

@mamedin has setup a VM for testing this. I've connected via ssh and created three transfers that you'll see when you browse:
```
	../TestTransfers/deep_transfer_12_deep_3961_files/
	../TestTransfers/deep_transfer_8_deep_1001_files/
	../TestTransfers/deep_transfer_8_deep_2002_files/
```
It might be a challenge to see the behaviour before the fix, but if you do ask @mamedin he can checkout AM as of `8593b7d5f96c23f037a085005adc8c7c96a2e200` for you, which should be before the fix, and *should* fail. I'm excited to see the current behaviour regardless! I wish I had time to get the Transfer in this morning! :D 

If need be, we can change the sample file we're copying `n` times. Right now it is just a markdown file with a couple of hundred bytes.

**Comment by currmie** [comment]
@jrwdunham - Using large transfers that @ross-spencer set up, tests no longer fail at METS creation but now fail in the Ingest tab during Index AIP.

**Comment by ross-spencer** [comment]
@jrwdunham @currmie I created a control set this morning using just a single file, and we are seeing an Elastic Search error. http://158.69.77.45/tasks/336c7769-083a-4038-8e17-bad50bf8330f/ - I think to begin, we should redeploy the latest version, I think we may have some undefined behaviour from isolating specific commits to test against previously. cc. @mamedin

**Comment by ross-spencer** [comment]
**Update:**

I had a think about the error and checked the status of ElasticSearch (ES). The error for a SIP/AIP with a single digital object being:
```
indexAIP.py: WARNING   2018-03-03 20:44:48,195  elasticsearch:log_request_fail:82:  PUT http://localhost:9200/aips [status:N/A request:10.004s]
Traceback (most recent call last):
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10.0)
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/indexAIP.py", line 121, in <module>
    sys.exit(index_aip())
  File "/usr/lib/archivematica/MCPClient/clientScripts/indexAIP.py", line 55, in index_aip
    client = elasticSearchFunctions.get_client()
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 155, in get_client
    create_indexes_if_needed(_es_client)  # TODO: find a better place!
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 200, in create_indexes_if_needed
    create_aips_index(client)
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 205, in create_aips_index
    create_index(client, 'aips')
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 271, in create_index
    response = client.indices.create(index, ignore=400)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 103, in create
    params=params, body=body)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10.0))
```
Trying the following with ES [link to checking it is running](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-16-04):
```
artefactual@am-issue-821:~$ curl -v -X GET 'http://127.0.0.1:9200/'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9200 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:9200
> Accept: */*
```
I wasn't receiving a response after a few minuts, so I restarted it:
```
artefactual@am-issue-821:~$ sudo service elasticsearch restart
 * Stopping Elasticsearch Server                                                                                                                                [ OK ] 
 * Starting Elasticsearch Server                                                                                                                                       artefactual@am-issue-821:~$ curl -v -X GET 'http://127.0.0.1:9200/'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9200 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:9200
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 339
< 
{
  "status" : 200,
  "name" : "Abomination",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.6",
    "build_hash" : "c730b59357f8ebc555286794dcd90b3411f517c9",
    "build_timestamp" : "2016-11-18T15:21:16Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
* Connection #0 to host 127.0.0.1 left intact
```
I have successfully ingest two simple SIPS.
```
ccdc7878-6543-4d5b-bf81-1a771bee131d
982aa56f-aa34-41de-93d0-f0cc9f9126a6
```
@currmie I am just trying a large ingest as we speak. If you're happy this all looks good, maybe give your tests another run, and see if we can get them in? - Fingers crossed they work. I wonder if their complexity maybe still got ES a little confused? I wouldn't be surprised if that's another outcome of this particular line of testing. I guess we'll see. 

Hope this helps :)

**Comment by currmie** [comment]
@ross-spencer Looks similar to the errors I had when trying a large ingest. Thanks for rebooting http://localhost:9200. Will kick off another run of tests.
