### ISSUE TITLE
Problem: sender e-mail address should be configurable

### ISSUE THREAD

**Issue by hakamine** [artefactual/archivematica#823]
Sender e-mail addresses such as [this](https://github.com/artefactual/archivematica/blob/4223fdc545758a778168128ce7b0f767c3735aef/src/MCPClient/lib/clientScripts/emailFailReport.py#L199) should be configurable, to be able to adapt to the organization's IT policy where the application is used.

**Comment by sevein** [comment]
See #813.

**Comment by jhsimpson** [comment]
I think #813 closes this issue?  @sevein is that true?

**Comment by sevein** [comment]
Yes I think that'd be the case.
The issue I created was https://github.com/artefactual/archivematica/issues/1128. I should have used this issue instead.

**Comment by sevein** [comment]
See #1128.
