### ISSUE TITLE
Problem: when search disabled, "Send to backlog" in processing config will break

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#826]
If Archivematica has been deployed with Elasticsearch (indexing) disabled and a transfer is initiated containing a processing MCP XML config file that sends completed transfers to backlog, the transfer will be sent to backlog but will not be retrievable via the GUI because the backlog tab is disabled with search is disabled.

Question: is this enough of an edge case that it can be left to documentation or do we want to spend time fixing this?

Fixing this would involve modifications to the MCPServer so that certain preconfigurations (e.g., "Send to backlog") are not permitted when certain abilities are disabled (e.g., search). We already have a new "abilities" module in AM for other recent ES-disabling work, so there is precedent and scaffolding for this work.

**Comment by jrwdunham** [comment]
Leaving this to possibly be fixed at a later date.

**Comment by sevein** [comment]
This is definitely fixed!
I think @jraddaoui did it.
