### ISSUE TITLE
Problem: Some required fields are unmarked in Handle server config

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#835]
Bind PIDs will fail if Archive resolve URL template and File resolve URL template are left blank, but they are not marked as required in the user interface.

**Comment by jrwdunham** [comment]
Should be fixed by https://github.com/artefactual/archivematica/pull/847.

**Comment by currmie** [comment]
Fix verified on test servers centos17x.qa and am17x.qa.
