### ISSUE TITLE
Problem: Handle server config page displays error

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#854]
The Handle server config page is displaying:

"Internal server error
Sorry! Something wrong happened. Please, contact with your administrator."

**Comment by jrwdunham** [comment]
@sromkey This should be fixed by https://github.com/artefactual/archivematica/pull/864 which is in stable/1.7.x and qa/1.x

**Comment by sallain** [comment]
Confirming that this looks to be fixed on our test servers.
