### ISSUE TITLE
Problem: metadata-only AIP re-ingest fails to initiate

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#863]
To reproduce:

1. Have an AM deploy running qa/1.x and SS qa/0.x
2. Create an AIP with no metadata.
3. Attempt to perform a metadata-only re-ingest on that AIP.
4. See the failure notification. (Expect to see a success notification and see the AIP in the ingest tab.)

This seems to be caused by the fact that the AIP's data/objects/metadata/ empty folder is getting deleted by `createMETS_v2.0` (because it's empty and BagIt doesn't like that), but then when one attempts a MO AIP re-ingest the SS will try to rsync a metadata/ folder that does not exist. This would appear to be a regression: the idea behind metadata-only re-ingest is that you can either update existing metadata, OR add metadata when it didn't already exist.

**Comment by jrwdunham** [comment]
INFO      2017-12-20 14:47:59  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/var/archivematica/storage_service/tmpF19XLq/BagTransfer_1513809807-cc66ada1-38bf-4576-9c66-067bedec4439/data/objects/metadata/', 'tmpF19XLq/BagTransfer_1513809807-cc66ada1-38bf-4576-9c66-067bedec4439/data/objects/metadata/']
    archivematica-storage-service_1  | WARNING   2017-12-20 14:47:59  locations.models.space:space:move_rsync:476:  Rsync failed with status 23: sending incremental file list
    archivematica-storage-service_1  | rsync: change_dir "/var/archivematica/storage_service/tmpF19XLq/BagTransfer_1513809807-cc66ada1-38bf-4576-9c66-067bedec4439/data/objects/metadata" failed: No such file or directory (2)
    archivematica-storage-service_1  | delta-transmission disabled for local transfer or --whole-file
    archivematica-storage-service_1  | total: matches=0  hash_hits=0  false_alarms=0 data=0
    archivematica-storage-service_1  |
    archivematica-storage-service_1  | sent 20 bytes  received 79 bytes  198.00 bytes/sec
    archivematica-storage-service_1  | total size is 0  speedup is 0.00
    archivematica-storage-service_1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]

**Comment by jrwdunham** [comment]
The cause of this would appear to ultimately be failing to have the Staging Path (`.staging_path`) set on my Local Filesystem Storage Service space. When this is not set, `package.py::start_reingest` has a relative path for the destination when moving the metadata/ TO the SS. As a result, when `local_filesystem.py::move_to_storage_service` calls `self.space.create_local_directory`, it does not create the destination `metadata/` directory. Since the source and destination are the same (after extracting an AIP, having `start_reingest` move it TO the SS is redundant because it is already in the internal processing location), we were paradoxically relying on behaviour where ensuring the destination directory was present was effectively creating the source metadata/ directory that is being "renamed" to the destination directory.

Failing to set the staging path may be a result of `make` rules in `am.git` (e.g., `make flush`) or it may be something in the SS code itself.

Two more fundamental SS code changes are required. 

1. The staging path should be required.
2. If a to-be-re-ingested file or directory is already in the SS's currently processing directory (as a result of extraction), then it should not be moved back to its current location as a way of indirectly creating that directory if it does not exist. If a metadata/ directory has been deleted, then metadata-only re-ingest should explicitly re-create that directory if that is what it needs to do.

**Comment by ross-spencer** [comment]
This issue mostly references a docker based deployment. Attempting this today on `1.10.x` shows that it is no longer a problem. I:

1. Created a transfer with just two jpegs. 
2. Waited for its ingest to complete.
3. Initiated a MD-only reingest. 
4. Saw that the MD-only reingest was awaiting approval in the ingest tab. 

Closing as it looks to have been resolved through various changes in AM since this was first reported. Should it be closed in error it can be reopened or a new issue created in https://github.com/archivematica/issues.
