### ISSUE TITLE
Problem: unable to access backlog after an upgrade from 1.6

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#865]
After upgrading from 1.6, the Apraisal tab doesn't work, and the archivematica dashboard log shows the following:

<pre>
INFO      2017-12-19 15:04:01  elasticsearch:base:log_request_success:63:  GET http://127.0.0.1:9200/transfers/transferfile/_search?size=50000
ERROR     2017-12-19 15:04:01  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /ingest/appraisal_list/
Traceback (most recent call last):
File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/share/archivematica/dashboard/components/ingest/views.py", line 646, in transfer_backlog
_es_results_to_appraisal_tab_format(path, directory_map, return_list, not_draggable=not_draggable)
File "/usr/share/archivematica/dashboard/components/ingest/views.py", line 556, in _es_results_to_appraisal_tab_format
if record['modification_date']:
KeyError: 'modification_date'
</pre>

**Comment by sevein** [comment]
@scollazo have you try to rebuild the Elasticseach indices?

**Comment by scollazo** [comment]
I think the root cause comes from 34986096f8c917fd0c6f8a6c50499406519baf82, commenting the line the reindex script works (but fails later...)

I tried the reindex script. but it doesn't work ( artefactual/archivematica-devtools#52 )

**Comment by sevein** [comment]
With https://github.com/artefactual/archivematica-devtools/issues/52 fixed by https://github.com/artefactual/archivematica/issues/894, is there anything else that we should be doing here?

**Comment by mamedin** [comment]
I tested the new rebuild-transfer-backlog command and it works fine.
👍

**Comment by nickwilkinson** [comment]
@mamedin can this issue be considered closed then?

**Comment by mamedin** [comment]
Yes, I'm going to close this issue now: fixed by #894

**Comment by sromkey** [comment]
@scollazo I'm leaving this assigned to you and in QA because at some point we'll need an upgraded instance to test this with.
