### ISSUE TITLE
Problem: CSV file not being added to METS metadata only AIP reingest workflow

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#870]
Just noticed that if I add a csv file to metadata only AIP reingest DC metadata isn't added to the METS file.  Tried to add the CSV before and after normalization on am17x.  Confirmed that this works in 1.6.1 (amdemo)

**Comment by jrwdunham** [comment]
@kellyannewithane I have tried to reproduce this issue and have failed. I will describe what I did below. Could you please let me know what steps you took to produce this issue?

1. I used a deploy of Archivematica at qa/1.x (commit 2e9ecb6e4484b1928e41b528d0947cc65223bdf8.)
2. I created an AIP from the transfer small/ containing only the text file small.txt. (This is in sampledata at archivematica-sampledata/TestTransfers/small/.)
3. Once the AIP was created, I initiated a metadata-only AIP re-ingest on it.
4. In the ingest tab while AM was waiting for my normalization decision, I clicked on the metadata (pen and paper) icon.
5. On the "Submission Information Package" page, I clicked the link "Add metadata files".
6. In the browse interface, I located a file called metadata.csv and I clicked the "Add" button/link to the right of it and then the green "Add files" button. This CSV file looks like

        filename,dc.title
        objects/small.txt,The Smallest File of All!

7. I then went back to the ingest tab and chose "Do not normalize" and waited for the ingest to complete and for the re-ingested AIP to be stored.
8. I downloaded the completed re-ingested AIP and uncompressed it and confirmed that
   a. the metadata.csv file is in the AIP at data/objects/metadata/metadata.csv,
   b. the metadata.csv file is listed in the AIP METS file in both the <mets:structMap> and <mets:fileSec>, and
   c. the DC metadata from the CSV file are associated to the small.txt file:

        <mets:dmdSec ID="dmdSec_865644" CREATED="2018-01-23T22:36:19" STATUS="original">
          <mets:mdWrap MDTYPE="DC">
            <mets:xmlData>
              <dcterms:dublincore xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xsi:schemaLocation="http://purl.org/dc/terms/ http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcterms.xsd">
                <dc:title>The Smallest File of All!</dc:title>
              </dcterms:dublincore>
            </mets:xmlData>
          </mets:mdWrap>
        </mets:dmdSec>
        ...
        <mets:structMap ID="structMap_1" LABEL="Archivematica default" TYPE="physical">
          <mets:div TYPE="Directory" LABEL="tue1-40ba25b4-64ae-4686-8726-dda6abb139a9" DMDID="dmdSec_1">
            <mets:div TYPE="Directory" LABEL="objects">
              <mets:div TYPE="Item" LABEL="small.txt" DMDID="dmdSec_865644">

**Comment by kellyannewithane** [comment]
@jrwdunham Tested in am17x.qa and can confirm that the above workflow you followed worked.  Closing issue.

**Comment by jrwdunham** [comment]
In the context of the AM 1.7 release, I think this issue can be considered "Done" since I followed the current documentation in order to add a metadata.csv file to an AIP/METS.

**Comment by slint** [comment]
I've tried following these instructions in AM v1.8.1, but my `metadata.csv` contents didn't update the existing AIP's METS metadata. Is there a special option or processing configuration (other than `Do not normalize`) I have to select during the re-ingest so that the `metadata.csv` updates the produced `METS.<AIP-id>.xml`? My `metadata.csv` looks like:

```
filename,dc.title,dc.description
objects/small.txt,Quack,Goes the duck!
```
When the re-ingest finishes and I download the file I have the following structure:

```~/Downloads/small-test-75d6a6bc-a939-4780-a3af-0386d18f2684 ⌚ 20:27:45
$ tree .
.
├── bag-info.txt
├── bagit.txt
├── data
│   ├── logs
│   │   ├── fileFormatIdentification.log
│   │   ├── filenameCleanup.log
│   │   └── transfers
│   │       └── small-test-c70b3141-0250-4eb2-8858-be50a0865e72
│   │           └── logs
│   │               ├── fileFormatIdentification.log
│   │               └── filenameCleanup.log
│   ├── METS.75d6a6bc-a939-4780-a3af-0386d18f2684.xml
│   ├── objects
│   │   ├── metadata
│   │   │   └── metadata.csv
│   │   ├── small.txt
│   │   └── submissionDocumentation
│   │       └── transfer-small-test-c70b3141-0250-4eb2-8858-be50a0865e72
│   │           └── METS.xml
│   └── README.html
├── manifest-md5.txt
├── manifest-sha256.txt
├── tagmanifest-md5.txt
└── tagmanifest-sha256.txt
```

The `data/objects/metadata/metadata.csv` is actually the file I added using the "Add metadata file" procedure.

Thanks in advance for any help.
