### ISSUE TITLE
Problem: Contributing guidelines refer to redmine not github for issue tracking

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#876]
the contributing.md file in this repo has details about how to file a bug.  Those instructions refer to the redmine instance at https://projects.artefactual.com  .  During the 1.7.0 release process, Artefactual staff have been using github to file new issues, and using projects.artefactual.com only for private client work (non-release work).  

The contributing.md file should be updated to reflect current practices.

**Comment by ross-spencer** [comment]
Closed via e9f1e89277eac5489a9b3adccf2580236bda6aac
