### ISSUE TITLE
Problem: headless feature needs to be included in 1.7 release

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#878]
Columbia University Library has sponsored development work to disable indexing in an Archivematica deployment.  This feature is scheduled to be included in the 1.7.0 release of Archivematica.

The complete list of items to merge before this feature can be considered complete:
- [x] Merge Archivematica PRs that bring in the indexless feature:
  - [x] [Archivematica PR 901](https://github.com/artefactual/archivematica/pull/901)
  - [x] [Archivematica PR 908](https://github.com/artefactual/archivematica/pull/908)
  - [x] [SS PR 328 which adds "delete" button](https://github.com/artefactual/archivematica-storage-service/pull/328)
- [x] Merge Acceptance Tests PRs that describe the expected behaviour:
  - [x] [Acceptance Tests PR 67 "Make indexless executable"](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/67).
  - [x] [Acceptance Tests PR 59 "Indexless Archivematica upgrade"](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/59)
- [x] Archivematica Docs PRs that describe how to install and upgrade Archivematica indexlessly:
  - [x] Merge [Archivematica Docs PR 73](https://github.com/artefactual/archivematica-docs/pull/73) which explains manual (package-based) installation of AM with and without ES indexing.
  - [x] Create and merge [AM-docs PR 77](https://github.com/artefactual/archivematica-docs/pull/77) for [Archivematica Docs Issue 74](https://github.com/artefactual/archivematica-docs/issues/74) which describes the need for instructions explaining how to upgrade AM from 1.6 to 1.7 with and without ES indexing.
- [x] Packaging (any changes from https://github.com/artefactual-labs/am-packbuild/commits/dev/build-dev-1.8-packages that are needed should be merged to master); related to am-packbuild issue https://github.com/artefactual-labs/am-packbuild/issues/108
- [x] Ansible headless deployment
  - [x] Merge [deploy-pub PR 52](https://github.com/artefactual/deploy-pub/pull/52).
  - [x] Merge [ansible-archivematica-src PR 171](https://github.com/artefactual-labs/ansible-archivematica-src/pull/171).

**Comment by sallain** [comment]
@kellyannewithane Assigned to you to update once the production deployment and upgrade issues have been worked out.
