### ISSUE TITLE
Problem: decision count notification circle on wrong tab in indexless deploy

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#910]
When Archivematica is deployed with indexing turned off, the backlog and appraisal tabs are not displayed. This causes the red circle that indicates awaiting decisions to be located on the access tab when it should be on the ingest tab. This is presumably caused by JavaScript logic assuming that the items in the navbar &lt;ul&gt; are constant.

**Comment by jrwdunham** [comment]
![image](https://user-images.githubusercontent.com/2504271/35835631-af9d9b74-0a90-11e8-8617-d75b1ec64f61.png)

**Comment by sromkey** [comment]
Assigning Kelly but we will need an indexless deploy for her to test.
