### ISSUE TITLE
Problem: AIP METS: PREMIS EVENTs sometimes have 2 agents instead of the expected 3

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#914]
I noticed an issue when running METS validation using metsrw's Schematron-based validator: some PREMIS:EVENTs have 3 PREMIS:AGENTs while others (e.g., the events for the transfer's METS.xml file) only have 2: they are missing the <premis:linkingAgentIdentifierType>Archivematica user pk agent. This is invalid given our Schematron file at https://github.com/artefactual-labs/mets-reader-writer/blob/master/metsrw/resources/archivematica_mets_schematron.xml#L125. Is this a problem with this Schematron file or is it an actual problem with the METS file we are constructing?

The error msg:

    Schematron Error(s):
    1. Each amdSec MUST contain 3 digiprovMD elements that contain
                mdWraps of MDTYPE PREMIS:AGENT
       test: count(m:digiprovMD/m:mdWrap[@MDTYPE = 'PREMIS:AGENT']) = 3
       location: /*[local-name()='mets' and namespace-uri()='http://www.loc.gov/METS/']/*[local-name()='amdSec' and namespace-uri()='http://www.loc.gov/METS/'][2]

Noticed during work on https://github.com/artefactual/archivematica/issues/907.

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/529.
