### ISSUE TITLE
Problem: MCPServer crashes (UnicodeEncodeError) with certain transfers

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#932]
Reported by @hakamine.

```
ERROR     2018-02-19 20:47:44  archivematica.mcp.server:archivematicaMCP:_except_hook_log_everything:627:  Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPServer/archivematicaMCP.py", line 660, in <module>
    watchDirectories()
  File "/usr/lib/archivematica/MCPServer/archivematicaMCP.py", line 487, in watchDirectories
    item = item.decode("utf-8")
  File "/usr/share/python/archivematica-mcp-server/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)
```

@hakamine also shared the name of the transfer:

```
# tree -sha /var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/
/var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/
└── [4.0K]  test_Cézanne
    └── [1.0K]  alavés.txt
```

The problem seems to be in `archivematicaMCP.watchDirectories()`:

https://github.com/artefactual/archivematica/blob/64b84f5e187eb605815e479263a81ca09f9e34f6/src/MCPServer/lib/archivematicaMCP.py#L484-L487

We seem to assume that the items returned by `os.listdir` are always binary. However the docs state the following:

> Changed in version 2.3: On Windows NT/2k/XP and Unix, if path is a Unicode object, the result will be a list of Unicode objects. Undecodable filenames will still be returned as string objects.

@jrwdunham suggests that we catch `UnicodeEncodeError` or check the type of `item` before decoding, e.g.:

```python
if isinstance(item, six.binary_type):
    item = item.decode("utf-8")
```

The root cause is not clear.

**Comment by nickwilkinson** [comment]
Hi @hakamine can you verify this working with the sample data?

**Comment by hakamine** [comment]
Already tested  (ref. #933)
