### ISSUE TITLE
Problem: not all directories recorded in structMap

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#934]
When testing PIDs using TestTransfers/acceptance-tests/pid-binding/hierarchy-with-empty-dir on am17x.qa

-physical and normative structMap don't record presence of dir2aiii, which should have ds_store object in it.  Instead, dir2aiii shows up in exifTool raw output

**Comment by jrwdunham** [comment]
To QA: create an AIP on pid-binding/hierarchy-with-empty-dir with PID binding (Handle) configured and confirm that the empty dir dir2aiii/ is in the METS file's normative logical structMap.

**Comment by ablwr** [comment]
Tested this. dir2aiii is present only in the raw exiftool data. And if I download the data and look inside, there is no dir2aiii folder (hence also nothing in it).

**Comment by ablwr** [comment]
😇  back to you!

**Comment by jrwdunham** [comment]
@ablwr I have confirmed that the am17x.qa machine did not have the commit from https://github.com/artefactual/archivematica/pull/935 that fixes this issue. I suspect that the centos17x.qa machine is the same way. The am17x.qa machine is in the process of being updated. I'll update here when centos17x.qa has been updated.

**Comment by jrwdunham** [comment]
@ablwr the am17x.qa machine should now work as expected when you try to QA this issue now.

**Comment by ablwr** [comment]
Test file works fine in am17x.qa. However, I wanted to run through the adjacent compressed test file and it seems to be having a bit of trouble making it through. @kellyannewithane and I are on it!

**Comment by ablwr** [comment]
Aforementioned issue is unrelated. This issue is fixed and LGTM!

**Comment by kellyannewithane** [comment]
Tested this on centos17x.qa and dir2aiii is present in physical and normative structmaps

**Comment by kellyannewithane** [comment]
Whoops yes sorry, you are correct @jrwdunham.  This feature is working as expected.
