### ISSUE TITLE
Problem: MCPServer magic links are deprecated

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#947]
We have some chains in the workflow that make use of [magic links](https://wiki.archivematica.org/MCPServer/TaskTypes#Magic_Links_-_Deprecated).

Because magic links were deprecated we should replace the chain links to make use of unit variables instead. This would simplify the code significantly.

**Comment by jhsimpson** [comment]
@sevein do you have a reference to when magic links were deprecated?

**Comment by sevein** [comment]
@jhsimpson I couldn't find much. I've found the [commit](https://github.com/artefactual/archivematica/commit/c69db38d2e426db381210b13727f46ff50cd3045) where the concept of unit variable was added. Magic links have been listed as deprecated in the [docs](https://wiki.archivematica.org/MCPServer/TaskTypes) since I started working on this project.
