### ISSUE TITLE
archivematica-mcp-server systemd unit fails to start to start after reboot

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica#953]
I was able to install Archivematica 1.7 RC on Ubuntu 16.04 using the instructions [here](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation/installation/#installing-ubuntu-packages).  After installing, I ran a reboot on the server.  After the server had restarted, the archivematica-mcp-server unit was in a failed state.

```
● archivematica-mcp-server.service - Archivematica MCP Server Service
   Loaded: loaded (/lib/systemd/system/archivematica-mcp-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-03-06 16:37:17 UTC; 27min ago
  Process: 1177 ExecStart=/usr/share/python/archivematica-mcp-server/bin/python /usr/lib/archivematica/MCPServer/archivematicaMCP.py (code=exited, status=1/FAILURE)
 Main PID: 1177 (code=exited, status=1/FAILURE)

Mar 06 16:37:17 ip-172-31-26-255 python[1177]:   File "/usr/share/python/archivematica-mcp-server/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in ge
Mar 06 16:37:17 ip-172-31-26-255 python[1177]:     conn = Database.connect(**conn_params)
Mar 06 16:37:17 ip-172-31-26-255 python[1177]:   File "/usr/share/python/archivematica-mcp-server/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
Mar 06 16:37:17 ip-172-31-26-255 python[1177]:     return Connection(*args, **kwargs)
Mar 06 16:37:17 ip-172-31-26-255 python[1177]:   File "/usr/share/python/archivematica-mcp-server/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 204, in __init__
Mar 06 16:37:17 ip-172-31-26-255 python[1177]:     super(Connection, self).__init__(*args, **kwargs2)
Mar 06 16:37:17 ip-172-31-26-255 python[1177]: django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Mar 06 16:37:17 ip-172-31-26-255 systemd[1]: archivematica-mcp-server.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 16:37:17 ip-172-31-26-255 systemd[1]: archivematica-mcp-server.service: Unit entered failed state.
Mar 06 16:37:17 ip-172-31-26-255 systemd[1]: archivematica-mcp-server.service: Failed with result 'exit-code'.
```

It was having difficulty connecting to MySQL.  MySQL, however, was running normally.

```
ubuntu@ip-172-31-26-255:~$ sudo service mysql status
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-03-06 16:37:18 UTC; 28min ago
  Process: 1249 ExecStartPost=/usr/share/mysql/mysql-systemd-start post (code=exited, status=0/SUCCESS)
  Process: 1161 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
 Main PID: 1248 (mysqld)
    Tasks: 44
   Memory: 225.6M
      CPU: 1.488s
   CGroup: /system.slice/mysql.service
           └─1248 /usr/sbin/mysqld

Mar 06 16:37:14 ip-172-31-26-255 systemd[1]: Starting MySQL Community Server...
Mar 06 16:37:18 ip-172-31-26-255 systemd[1]: Started MySQL Community Server.
```

The issue appears to be that a dependency on MySQL is not being set up in the archivematica-mcp-server unit at /lib/systemd/system/archivematica-mcp-server.service.  I was able to fix this by altering the _After_ line to read as follows:

```
After=syslog.target network.target mysql.service
```

The unit file installed by the deb should be updated with a revised unit file using this line.

**Comment by scollazo** [comment]
As there are more than one package providing mysql services (the "official" mysql-server package, percona and mariadb), I think a better aproach would be to implement a connection retries in mcp-server.

Also, there are environments where mysql is in it's own server,  instead of being installed in the same server than mcp-server and dashboard, so changing the systemd script won't help there.

**Comment by jpellman** [comment]
On this point-

a) Which one of the above packages (MySQL, Percona, MariaDB) is listed in your debian/control file?  How about you use that one?  Implementing connection retries does not fix the root issue, which is that services are not being loaded in the correct order by systemd.  Think of it this way- if you were implementing this with SysVinit, and both services started up in runlevel 3, and archivematica-mcp-server was failing because its init script was named S63archivematica-mcp-server and MySQL's init script was named S64mysql, wouldn't it make sense to just rename the archivematica-mcp-server init script to start with 'S65' instead of 'S63' to ensure that it ran after MySQL started?  That's essentially what you're doing when you create a dependency via _After_ in a systemd unit file.

b) Presumably (although I don't know for sure), the packagers of MariaDB and Percona have considered that other unit files might expect a service unit file named 'mysql.service', rather than one named 'mariadb.service' or 'percona.service', and have created a symlink from mysql.service to mariadb.service (or whatever) with their packages.  This might be worth checking.

c) The installation instructions don't mention installing mcp-server and MySQL server on separate hosts until the _Advanced_ section at the very end, and even then there are no concrete steps for creating this setup and it does not seem within the scope of standard support you provide.  Your average end-user is not going to do this, and even if this were something someone would want to do, you presumably wouldn't be using the same archivematica-mcp-server package that I was using before, since that package **automatically** brings in some flavor of MySQL as a dependency.  

Even if I were separating Archivematica and its dependencies across multiple hosts, I would expect the MCP server service to fail if my database server were not working- this would give me (the sysadmin) valuable feedback (I forgot to start my database server or it's down due to cause X).  What I **do not** expect is that, upon reboot on a standard, single-host Archivematica installation I find that the MCP server has failed to start, citing inability to connect to the MySQL server and yet the MySQL service is humming along with no obvious issues.

**Comment by scollazo** [comment]
I fully get your concerns, both rpm and debian mcp-server packages have been updated following your request

Thanks for taking the time to explain your case

**Comment by jpellman** [comment]
Awesome, thanks!

**Comment by sevein** [comment]
I think it's ok to assume that deb/rpm packages target single-node environments. I don't know if this is stated explicitly but we should probably do so.
