### ISSUE TITLE
Problem:  apps.nationalarchives.gov.uk is an obsolete URL

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#968]
It appears here in the code base:

https://github.com/artefactual/archivematica/blob/0c748d9f448b8d18961fc8cb764c0149e56fd11b/src/dashboard/frontend/appraisal-tab/app/report/format.html

The National Archives, UK, made this obsolete, as per this notice here:

https://groups.google.com/forum/#!searchin/droid-list/apps%7Csort:date/droid-list/ZM0OyvR7cA8/oEVbfpqFBgAJ

While the redirect should remain active, we should keep the URL up to date with TNA's own practices.

**Comment by ablwr** [comment]
LGTM! You can see the change when you look at the links to formats in the FPR.
