### ISSUE TITLE
Problem: FPR server should be decoupled from Archivematica

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica#970]
The FPR was originally created to manage preservation plans, i.e. business rules and tool commands for format-based preservation events. The FPR server’s purpose has been to house the default rules and commands while allowing institutions to make local alterations as desired.

Going forward, it is advisable to remove Archivematica’s dependency on the FPR server for the following reasons:

- The FPR rules on the FPR server are out of date. When new rules are added to the Preservation Planning tab in Archivematica, they aren't always being copied back to the FPR server.
- Currently, new Archivematica installations ping the FPR server, which records the IP address of the remote server. This data capture isn't useful and it isn’t necessary.

Removing the FPR server as a dependency in future versions should not impact how Archivematica is being used previous to 1.7.

The longer-term goal would be to build a new FPR server, one that is completely decoupled from Archivematica, which would serve up format policy data to other applications using an open API. This future registry would not rely on a single vendor for maintenance.

**Comment by sevein** [comment]
#971 changed AM17 so it doesn't make use of FPRServer.

I'm not going to close this issue so we can use it to track our future intentions.

**Comment by ablwr** [comment]
I wonder if this ticket ought to be closed, as future intentions have grown and become somewhat divergent? It seems discussion is likely to end up in other places.

**Comment by sromkey** [comment]
I agree @ablwr , I'm going to go ahead and close it! FPRServer has been successfully decoupled as of 1.7.
