### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by cdekok** [artefactual/archivematica#978]
The changelog seems to be neglected since 1.5.0: https://github.com/artefactual/archivematica/blob/stable/1.7.x/CHANGELOG.md
Is there any other place to find the changes between 1.5.x and 1.6.x and eventually 1.7.x?

**Comment by scollazo** [comment]
I tihnk the best place would be the release notes , available at https://wiki.archivematica.org/Archivematica_1.6_release_notes and https://wiki.archivematica.org/Archivematica_1.7_release_notes (this one, still a work in progress)

**Comment by sevein** [comment]
@scollazo @cdekok please let me know if #985 would be enough to close this issue.

**Comment by cdekok** [comment]
Well yeah sure it can be closed but to be honest a changelog in the repo is really useful when it comes to upgrading the software, it seems it was carefully done on the 1.5 release but after that neglected for some reason?
If the wiki has become the main source for the changelog perhaps it could be added as comment in the file or removed altogether.

**Comment by sevein** [comment]
> If the wiki has become the main source for the changelog perhaps it could be added as comment in the file or removed altogether.

PR 985 is all about that, have you seen it?
