### ISSUE TITLE
Problem: Language screen wording needs to be changed

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#996]
On the language screen, an admonition below the language options reads "Your choice will be recorded in the internal session store which **doesn't not** retain data forever." This should be changed.

**Comment by jrwdunham** [comment]
Cherry-picked to stable/1.7.x as 386dbb7832191cac1926dc5cd7a5a8337f9686aa

**Comment by jrwdunham** [comment]
To QA: deploy AM and navigate to the Language page and confirm that the text reads "Your choice will be recorded in the internal session store which does not retain data forever."

**Comment by sallain** [comment]
Looks good, @jdunham :)
