### ISSUE TITLE
Problem: Validation events aren't making it into the Transfer METS.xml on Transfer

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/archivematica#998]
I have created a SIP on Augustus and sent it to [backlog](http://augustus.qa.archivematica.org/tasks/bc9f9ae4-18bb-415f-8c2e-48d734e21012/) the log confirmats that files that have been passed onto JHOVE for validation but if I review the METS in Backlog ([download link](http://augustus.qa.archivematica.org/backlog/download/74367005-4470-4fa8-900b-1ce8760c533e)), the validation events for these objects aren't there. 

Can anyone help me confirm this?

(Further, but this might be a misunderstanding reading the METS at this stage, but I see PREMIS events for identification and virus scan, but they don't seem to be linked back to the digital objects properly? - Am I reading this incorrectly too?)

**NB.** I am seeing this in my own QA environment as well.

**Comment by ross-spencer** [comment]
This does not seem to be a regression, and can be observed in the 1.6 release via http://sandbox.archivematica.org. It seems we may need to review the content of the METS/PREMIS at this phase of the workflow where certain events related to the digital objects have already happened.

**Comment by ross-spencer** [comment]
Further, reviewing the AIP, the information does seem to be present there (1.6). 

It seems that another difference between the Transfer METS and AIP METS is that `            <premis:originalName>%transferDirectory%objects/Club-Report.doc</premis:originalName>` doesn't seem to exist in the Transfer METS which (I think) means the PREMIS events can't be linked back to their original objects - not until the Backlog SIP is turned into an AIP.

**Comment by peterVG** [comment]
I can confirm on AM 1.8 that, while Validate events are successfully occurring during transfer, they are not being written to the backlog METS file as premis:eventTypes. They do, however, appear in the AIP METS xml as premis:eventTypes. Other transfer premis:eventTypes are being written to the transfer backlog METS file including ingestion, message digest calculation, fixity check, virus check, and format identification.

**Comment by peterVG** [comment]
Also, while the `premis:originalName` value is not included in the transfer METS, the PREMIS events in the Transfer METS can still be linked to their original objects via the `mets:fileSec` which links the original object to its amdSec via an `ADMID`.

**Comment by ross-spencer** [comment]
Looking at something around this recently, the only reference to outputting `amdsecs` in the transfer that I could find was this microservice: https://github.com/artefactual/archivematica/blob/707e9332f0bebf4c32def012e30752314a207d48/src/MCPClient/lib/clientScripts/create_processed_structmap.py#L14-L27 `Job: Add processed structMap to METS.xml document`

If you look at the workflow it happens quite early:

![image](https://user-images.githubusercontent.com/1880412/50083390-e7d9c480-01f3-11e9-8031-2b23c70ce083.png)

So, a possible thing to try could be moving this microservice much later in the workflow (it doesn't really need to be so early) and the PREMIS events for validation might be output as part of that. This is really just a hypothesis at this stage rather than any concrete position.

**Comment by sevein** [comment]
@ross-spencer I think you're right. It's also clear by looking at the graph that "Validate formats" is not execute before but after "Add processed structMap to METS.xml document". The latter is responsible for saving the events. 

![image](https://user-images.githubusercontent.com/606459/52152308-cd846a80-262a-11e9-94f6-b3ebe0c38ad2.png)

**Comment by sallain** [comment]
I ended up having to test something related to validation, so I can confirm that validation events now appear in the transfer METS:

```
    <mets:digiprovMD ID="digiprovMD_302" CREATED="2019-07-11T21:01:44">
      <mets:mdWrap MDTYPE="PREMIS:EVENT">
        <mets:xmlData>
          <premis:event xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
            <premis:eventIdentifier>
              <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
              <premis:eventIdentifierValue>639c7962-d929-4e96-bdc5-1964d595c8c8</premis:eventIdentifierValue>
            </premis:eventIdentifier>
            <premis:eventType>validation</premis:eventType>
            <premis:eventDateTime>2019-07-11 21:01:43.997464+00:00</premis:eventDateTime>
            <premis:eventDetailInformation>
              <premis:eventDetail>program="JHOVE"; version="1.20"</premis:eventDetail>
            </premis:eventDetailInformation>
            <premis:eventOutcomeInformation>
              <premis:eventOutcome>partial pass</premis:eventOutcome>
              <premis:eventOutcomeDetail>
                <premis:eventOutcomeDetailNote>format="TIFF"; version="6.0"; result="Well-Formed, but not valid"</premis:eventOutcomeDetailNote>
              </premis:eventOutcomeDetail>
            </premis:eventOutcomeInformation>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>Archivematica-1.10</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>AM qa/1.x SS qa/0x</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
            <premis:linkingAgentIdentifier>
              <premis:linkingAgentIdentifierType>Archivematica user pk</premis:linkingAgentIdentifierType>
              <premis:linkingAgentIdentifierValue>1</premis:linkingAgentIdentifierValue>
            </premis:linkingAgentIdentifier>
          </premis:event>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:digiprovMD>
```
